src/DiffEqBase.jl, src/problems/functions.jl
Concering comment https://github.com/JuliaDiffEq/Roadmap/issues/5#issuecomment-260681959:
I only saw the `jac_exists` function after I put this together.  However, neither `has_jac` nor `jac_exits` passes the test in above comment.
However, when using a trait-function it would be fully inferred.  Note however, that the traits would struggle with adding, say a jacobian, to the function.  It may would still dispatch to the wrong one.
=> WIP: Function interface specs

.travis.yml, appveyor.yml, src/solutions/solution_interface.jl
The most precise way to specify which variables to plot is to pass a
list of tuples `(x, y)` where `x` and `y` are positive integers to
indicate the corresponding dependent variable, or 0 to refer to time
(the independent variable).  Example:
vars = [(0,1), (1,3), (4,5)]
will plot on the same graph `sol[1]` as a function of `t`, `sol[3]` as a
function of `sol[1]`, and `sol[5]` as a function of `sol[4]` (whatever
that could mean).
Everything could be done with that, but for convenience several
shortcuts are allowed:
* Everywhere in a tuple position where we only find an integer, this
variable is plotted as a function of time.  For example, the list above
is equivalent to:
vars = [1, (1,3), (4,5)]
and
vars = [1, 3, 4]
is the most concise way to plot the variables 1, 3, and 4 as a function …
=> Add a `vars` parameter to plot phase diagrams

src/problems/discrete_problems.jl
This is necessary for type-checking when creating new jump problems from old ones, see [JuliaDiffEq/DiffEqJump.jl/pull/4](https://github.com/JuliaDiffEq/DiffEqJump.jl/pull/4).
=> Defined constants for default f used by DiscreteProblem

src/DiffEqBase.jl, src/typemacros.jl, src/typemacros5.jl, src/typemacros6.jl
This change eliminates all of the deprecation warnings about `abstract` types in DiffEqBase, when building under v0.6.
=> Use new macros to simplify code and eliminate deprecation warnings in v0.6

src/solutions/monte_solutions.jl
I don't think there is any reason `MonteCarloSolution` constructor should work without taking `converged` as an argument. I also forgot about `MonteCarloTestSolution` in the last PR. I guess I should have run tests on both DiffEqBase and my changes to DiffEqMonteCarlo.  I don't think there is anything else I should need to change in base for the basic reduction functionality to work.
=> MonteCarloSolution always takes converged

src/parameters_interface.jl, test/parameters_interface_test.jl
Added a dispatch option for `set_param_value!` which will give nice options to set parameters for when the `ode_def` macros are used. Also added some basic tests.
=> Add Dict dispatch for `set_param_value!`

src/parameters_interface.jl
Hi!
It seems there is a small typo in the creation of new DDE problems with changed parameters:
```julia
julia> type TestFunction <: AbstractParameterizedFunction{true}
α::Float64
end
julia> (f::TestFunction)(t,u,h,du) = f(t,u,h,[f.α],du)
julia> function (f::TestFunction)(t,u,h,p,du)
du[1] = p[1]*h(t-1)[1]
end
julia> prob = ConstantLagDDEProblem(TestFunction(1),t->ones(1),[1.],[1.],(0.,10.))
julia> prob2 = problem_new_parameters(prob,[2.])
ERROR: MethodError: no method matching DiffEqBase.DAEProblem(::DiffEqBase.##250#252{DiffEqBase.ConstantLagDDEProblem{Array{Float64,1},Float64,Array{Float64,1},true,TestFunction,##1#2,Void,UniformScaling{Int64}},Array{Float64,1}}, ::##1#2, ::Array{Float64,1}, ::Array{Float64,1}, ::Tuple{Float64,Float64})
Closest candidates are: …
```
=> Fix new DDE problem with changed parameters

src/utils.jl, test/muladd.jl, test/runtests.jl
Hi!
As a reaction to https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/86#issuecomment-317954326, this PR changes the current implementation of `@muladd` in the following ways:
* Conversion of combined multiplication and addition into a call of `muladd` is applied recursively
* If one of the operands or operators (i.e. one of `x`, `y`, `z`, `+`, `*` in the expression `x*y+z`) is a dot call, `muladd` is also applied as a dot call, resulting in `muladd.(x,y,z)`
This is a first step towards fixing https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/86#issuecomment-317954326, since with this new implementation use of `@muladd` in https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/verner_rk_integrators.jl leads to the following expressions:
```julia
julia> …
```
=> Recursive and dotted replacement with muladd

src/DiffEqBase.jl, src/data_array.jl, test/data_array_tests.jl, test/runtests.jl
These are some changes to `DEDataArray` we discussed in https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/64. Since the implementation here is quite different to the other PR and does not contain any specific broadcast methods, I thought it might be cleaner to open a separate PR and close the old one.
`DEDataArray{T,N}` is now a subtype of `AbstractArray{T,N}`, which seems more natural. Of course, if the wrapped array `x` is not of type `AbstractArray{T,N}` the desired behaviour and propagation of `x` won't work but I guess that's a problem the user has to deal with.
Moreover I defined the convenient aliases `DEDataVector` and `DEDataMatrix`. I removed unneeded methods of the AbstractArray interface which will just work because of their defaults in Base, so e.g. only one implementation of …
=> Change DEDataArray implementation

src/diffeq_operator.jl, test/affine_operators_tests.jl, test/runtests.jl
`size` is necessary for F*u. The sizes of the constituent operators
have to agree as well, for the sum to be defined.
NB. To not depend on OrdinaryDiffEq.jl for testing, I implemented a dummy operator consisting only of size information.
=> Implemented size method for AffineDiffEqOperators

src/DiffEqBase.jl, src/diffeq_operator.jl
Should there be more traits?
I chose not to set `has_expmv(!)` for `AbstractDiffEqLinearOperator` since they fall back on the less efficient `expm`.
=> Linear ops traits

src/DiffEqBase.jl, src/callbacks.jl, src/data_array.jl
This adds an abstract type of continuous callbacks which helps to add a special subtype of continuous callbacks to track discontinuities in DelayDiffEq.
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/186, and hence also https://github.com/JuliaDiffEq/DelayDiffEq.jl/pull/34 and https://github.com/JuliaDiffEq/DelayDiffEq.jl/pull/35 depend on this PR.
=> Add AbstractContinuousCallback

src/parameters_interface.jl
During parameter estimation I discovered that the parameter interface is not implemented for `DDEProblem`. E.g. in DiffEqParamEstim in line
https://github.com/JuliaDiffEq/DiffEqParamEstim.jl/blob/master/src/build_loss_objective.jl#L43
an implementation of `num_params` is required, which currently uses the fallback of `0` for `DDEProblem`. I added the usual implementation. I haven't tested the new problem generator function since I work with a custom generator.
=> Implement parameter interface for DDEProblem

deps/build.jl
(requires new tag release to take effect)
This message is displayed as an info when a user updates `DiffEqBase` (so, *any* package of the ecosystem).
It is displayed only once, during the update, because the script here triggers the "Pkg.build" after the update.
*I am not sure whether this is triggered multiple times if one updates multiple times.* I am sure however that this does not trigger on `using ...`, only updates.
=> Add update warning

REQUIRE, src/DiffEqBase.jl, src/internal_euler.jl, src/tabletraits.jl, test/runtests.jl, test/tabletraits_tests.jl
This moves the iterable tables integration from IterableTables.jl into this repo here.
Tests don't pass right now, I think mainly because I don't understand DiffEqBase well enough and the way these problems are setup doesn't work anymore with the new DiffEqBase release. My hope is that @ChrisRackauckas can point out how to change these in negative time.
A bigger questions is probably whether these tests should depend on ParameterizedFunctions.jl or not. Right now the last test does. Not sure what the best choice is there.
The corresponding PR on the IterableTables.jl side is https://github.com/davidanthoff/IterableTables.jl/pull/72. Ideally we should tag new versions of both packages roughly at the same time with these two PRs merged.
=> WIP Add TableTraits.jl interface for solutions

src/DiffEqBase.jl, src/problems/analytical_problems.jl, src/problems/bvp_problems.jl, src/problems/dae_problems.jl, src/problems/dde_problems.jl, src/problems/discrete_problems.jl, src/problems/monte_problems.jl, src/problems/noise_problems.jl, src/problems/ode_problems.jl, src/problems/rode_problems.jl, src/problems/sde_problems.jl, src/problems/steady_state_problems.jl, src/utils.jl, test/remake_tests.jl, test/runtests.jl
closes https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/230
=> Add remake() for reconstructing immutable structs

src/DiffEqBase.jl, src/integrator_interface.jl, test/integrator_tests.jl, test/runtests.jl
closes https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/253
This PR bundles some related changes:
* Tweak `step!(integrator, dt)` to return the actual advanced step.
* Add `set_t!(integrator, t)`
* A few tests for integrator interface.
* Fixed a typo/bug in `step!`
=> Tweak and fix step!, add set_t!

src/DiffEqBase.jl, src/integrator_interface.jl
This implements https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/252 at the abstract level for all DiffEq integrators using `step!` and the generic `get_tmp_cache` interface. It uses one cache value and mutates, so it assumes the user knows to not save the pointer of `u`.
However, since DiffEqBase doesn't have a full integrator implementation a test can't reside here. A downstream test was created:
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/320
which is:
```julia
using OrdinaryDiffEq, DiffEqProblemLibrary, RecursiveArrayTools
integrator = init(prob_ode_2Dlinear,Tsit5();dt=1//2^(4))
ts = linspace(0,1,11)
us = Matrix{Float64}[]
for (u,t) in TimeChoiceIterator(integrator,ts)
push!(us,copy(u))
end
@test VectorOfArray(us) ≈ integrator.sol(ts)
```
@simonbyrne this is …
=> time choice iterator

src/integrator_interface.jl
Once https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/319 and https://github.com/JuliaDiffEq/StochasticDiffEq.jl/pull/74 are merged, there is no need to call `check_error!` in `done` since it is already called in `step!` (via `next`).
If `check_error!` (or in particular `postamble!`) is idempotent then the old code should be OK.  If so, maybe it's better to not pull this PR for a while, until all DiffEq downstreams call `check_error!` in `step!`.
=> Check sol.retcode in done

src/integrator_interface.jl, test/integrator_tests.jl
In `step!(integrator, dt)`, `integrator.sol.retcode` has to be checked since otherwise it could enter into an infinite loop.
See: https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/319 and https://github.com/JuliaDiffEq/StochasticDiffEq.jl/pull/74
=> Check sol.retcode in step!(integrator, dt)

src/DiffEqBase.jl, src/utils.jl, test/export_tests.jl, test/runtests.jl
Here is a way to fix UndefVarError quirks (see also https://github.com/JuliaDiffEq/diffeqpy/pull/24#issuecomment-384885291).  I was half unsure if it's just end up being a yet another nitpick but I found that `include("alg_traits.jl")` is missing while making this PR.  I'm not sure if it is intentionally removed.  But if the intention was to add `include("alg_traits.jl")`, I think it actually make sense to include such test, at least in `DiffEqBase`, to make sure that the interface functions are correctly exported.
If we are to apply this to other packages, each package "just" have to add a one-linear test. For example, for `OrdinaryDiffEq`:
```julia
@test DiffEqBase.undefined_exports(OrdinaryDiffEq) == []
```
Fixing a package (say `OrdinaryDiffEq`) is less cumbersome, e.g., if you use …
=> Remove undefined exports

src/solutions/monte_solutions.jl
Add an option to pass a `zcolor` for each series of an `AbstractMonteCarloSolution`.
=> Add zcolors

src/diffeqfunction.jl, src/utils.jl
Previously we need to explicitly specify `iip` both when constructing a `DiffEqFunction` and when creating an `ODEProblem` from a `DiffEqFunction` (if `f` is an in-place `DiffEqFunction` and `prob = ODEProblem(f, u0, tspan)`, then `prob` will be incorrectly classified as out-of-place. This update should fix the problem.
```julia
_f = (u,p,t) -> u
_fip = (du,u,p,t) -> du .= u
f = DiffEqFunction(_f)
fip = DiffEqFunction(_fip);
```
```julia
isinplace(f, 4)
```
false
```julia
isinplace(fip, 4)
```
true
```julia
prob = ODEProblem(f, rand(2), (0.0, 1.0))
```
DiffEqBase.ODEProblem with uType Array{Float64,1} and tType Float64. In-place: false
timespan: (0.0, 1.0)
u0: [0.710152, 0.0412191]
```julia
prob = ODEProblem(fip, rand(2), (0.0, 1.0))
```
DiffEqBase.ODEProblem with uType Array{Float64,1} …
=> Better in-place detection for `DiffEqFunction`

src/DiffEqBase.jl, src/data_array.jl, src/diffeq_operator.jl, src/diffeqfunction.jl, src/linear_nonlinear.jl, src/problems/discrete_problems.jl, src/solutions/ode_solutions.jl, test/diffeqfunction_tests.jl, test/problem_creation_tests.jl
This PR aims to fix a test failure in https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/392, i.e.
```julia
prob = DiscreteProblem(0.5,(0.0,1.0))
sol = solve(prob,FunctionMap())
```
It also fixs some depwarns by `LinearAlgebra` and `Statistics`.
=> 0.7 compatibility

src/diffeqfunction.jl, src/problems/bvp_problems.jl, src/problems/dae_problems.jl, src/problems/dde_problems.jl, src/problems/ode_problems.jl, src/problems/rode_problems.jl, src/problems/sde_problems.jl, src/problems/steady_state_problems.jl, test/remake_tests.jl
To address https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/416#issuecomment-405622364, the `jac_prototype` field is moved from `*DEProblem` to `*DEFunction`. In addition, `f.jac` is automatically set to use `update_coefficients!` if the constructor is given a `AbstractDiffEqLinearOperator` and no custom jacobian update function is given (for out-of-place `f`, first a copy is made from `jac_prototype` and then `update_coefficients!` is called on the copy).
=> Update handling of `jac_prototype`

src/diffeqfunction.jl
Forgot to update the autosetting of `jac` for `ODEFunction` to differentiate between in-place and out-of-place in #123. This should fix it.
=> Hotfix for #123

src/diffeqfunction.jl, src/parameters_interface.jl, src/problems/bvp_problems.jl, src/problems/dde_problems.jl, src/problems/ode_problems.jl, src/problems/rode_problems.jl, src/problems/sde_problems.jl, src/problems/steady_state_problems.jl, test/remake_tests.jl
These are the proposed changes to how mass matrix should be handled in DiffEq. Basically, the `mass_matrix` field is no longer stored as a field of `*DEProblem` but instead `*DEFunction`.
The main reason for these changes is to make sparse/lazy W operator handling in OrdinaryDiffEq simpler https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/416#issuecomment-405622364. Apart from this, there are also be cases where knowing what the mass matrix is solely by querying the `*DEFunction` might help. One case I can think of is converting a problem with non-unity mass matrix to a regular problem, i.e. `Mu' = f(u)` -> `u' = M^(-1)f(u) = g(u)`. Since a lot of integrators do not use the mass matrix explicitly (e.g. the ExpRK integrators) this can come handy. By storing `mass_matrix` in …
=> Mass matrix change

src/diffeqfunction.jl
Makes the `has_*` predicates work the same on `SplitSDEFunction` as `SplitFunction`. Needed for https://github.com/JuliaDiffEq/StochasticDiffEq.jl/pull/96.
=> Fix SplitSDEFunction traits

src/solutions/solution_interface.jl
Otherwise you get error like `MethodError(keys, (getfield(DiffEqBase, Symbol("##78#84"))(Core.Box((70, 90))),), 0x0000000000006c9b)`.  I'm sending a PR to 07-fix branch since Plots.jl is not ready yet for 1.0.
It fixes some semantics of the previous code.  Reading the code history, I _guess_ this is the correct implementation.  But rest of the plotting function is so large and I'm not 100% sure about this...
=> Fix plot(sol, tspan=...)

src/interpolation.jl
Have been migrating a few simple projects through the 0.7-1.0 process and hit a depreciation that might have been overlooked:
> ┌ Warning: `Array{T, 1}(m::Int) where T` is deprecated, use `Array{T, 1}(undef, m)` instead.
> │   caller = interpolation(::Array{Float64,1}, ::Function, ::Nothing, ::Type, ::Array{Float64,1}) at interpolation.jl:44
> └ @ DiffEqBase ~/.julia/packages/DiffEqBase/mKOqQ/src/interpolation.jl:44
There are three initialisation calls here that need `undef` included now&mdash;a simple enough fix.
=> Fix initialisations in interpolation method

REQUIRE, src/DiffEqBase.jl, src/data_array.jl
Hi!
With this PR, the functions `recursivecopy!` and `copy_fields!` are improved by considering the field type when copying.
This partially fixes the bug JuliaDiffEq/DifferentialEquations.jl#336, because it is now possible to use `SArray` as a field type in `DEDataVector`.
=> Improve recursivecopy! and copy_fields! considering the types when copying

src/problems/bvp_problems.jl
The first example (pendulum) in the [docs](http://docs.juliadiffeq.org/latest/tutorials/bvp_example.html) threw the following error:
```julia
ERROR: MethodError: no method matching has_analytic(::typeof(simplependulum!))
Closest candidates are:
has_analytic(::DiffEqBase.AbstractDiffEqFunction) at C:\Users\Attila\.julia\packages\DiffEqBase\YSk7M\src\diffeqfunction.jl:466
```
I checked the commits and it seems the constructor for the `BVProblem` was not updated in PR #147, so the input function is not converted to the `ODEFunction`.
With these changes the example now works properly and it seems I did not break anything, however feel free to comment if this messes up anything else.
=> Fix BVProblem constructor

src/init.jl
Ref https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/152\#issuecomment-417401398.
I guess `dual_number_warn` is also broken in the same way, right? 
I don't know how I feel about this whole setup by the way. What makes these two special?
=> Fix for method ambiguity errors with dual_number_warn and measurements_warn

src/init.jl, src/solve.jl
This deserves an explanation. While fixing https://github.com/JuliaDiffEq/DiffEqSensitivity.jl/issues/24 I noticed that using dual numbers to get sensitivities worked with `saveat` but could give incorrect values on the directly saved values. This seemed odd, and I tracked it down to being due to adaptive time stepping by turning off adaptivity and seeing it go away. `saveat` values have no sensitivity/uncertainty in time, so that made sense as well.
But to fix it, I implemented the change of this PR. What this essentially does is it separates time from the dual valued state space. This has been a long running noted oddity that in order to differentiate you needed to set time to dual numbers as well (though this issue points out it was only correct with `saveat`, which all parameter …
=> Fix sensitivities and don't require time to be dual valued

src/solutions/solution_interface.jl
`logspace` does not work anymore in Julia 1.0. I replaced it with `10.0^range(...)` because of an error when using `plot` from Plots.jl
=> logspace replace by base.^range(..)

src/problems/steady_state_problems.jl, test/problem_creation_tests.jl
Is it OK to assume `prob.p` exists for any `AbstractODEProblem`?
=> Pass p of ODEProblem to SteadyStateProblem

src/callbacks.jl
I've been griping about the issue is that the tolerance is impossible to set because it's not dependent on `t` but the callback function itself. Examples:
```
using Roots
f(x) = exp(x) - x^4
x = find_zero(f, (8,9), Roots.AlefeldPotraShi())
f(x) # 9.094947017729282e-13
f(nextfloat(x)) # 7.275957614183426e-12
f(prevfloat(x)) # -1.8189894035458565e-12
f(x) = 1e8 - (x+5)^11
x = find_zero(f, (0,16), Roots.AlefeldPotraShi(), atol = 0)
f(x) # 2.9802322387695312e-8
f(nextfloat(x)) # -1.4901161193847656e-7
f(prevfloat(x)) # 2.9802322387695312e-8
f(x) = 100000000000000*(x-8)
f(8.0) # 0.0
f(prevfloat(8.0)) #-0.08881784197001252
f(nextfloat(8.0)) #0.17763568394002505
```
Then it dawned on me that we can just use the callback's output itself as its next tolerance. If we always prevfloat, then the …
=> use callback tolerance from last event

src/callbacks.jl
@MSeeker1340 I noticed that `saved_in_cb` wasn't being set even when the callbacks were saving. This fixes a lot of tests in DiffEqCallbacks.jl. Testing to see what happens to other packages before merging.
=> fix saved_in_cb

src/callbacks.jl
Testing OrdinaryDiffEq reveals that the latest commits break callbacks: `AlefeldPotraShi` is not exported by Roots.jl.
=> Fix callbacks

src/callbacks.jl, src/integrator_interface.jl
The reason that we are doing this is that checking `last(integrator.sol.t) == integrator.t` is not a nice solution. Instead, we can just make `savevalues!` return `saved, savedexactly`. This PR can be merged after merging and tagging https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/544, https://github.com/JuliaDiffEq/DelayDiffEq.jl/pull/86, https://github.com/JuliaDiffEq/StochasticDiffEq.jl/pull/113, https://github.com/JuliaDiffEq/Sundials.jl/pull/191, and https://github.com/JuliaDiffEq/ODEInterfaceDiffEq.jl/pull/15. In this way, we won't introduce any breaking changes.
All tests passed locally:
```julia
julia> @time @safetestset "Event Tests" begin
home = homedir()
rt = "$home/.julia/dev"
cdir = pwd()
cd(rt)
println("OrdinaryDiffEq")
@safetestset "OrdinaryDiffEq" begin …
```
=> `savevalues!` should return booleans

src/diffeqfunction.jl
Currently DiffEqBiological can get syms to appear in plot legends for ODEs and SDEs, but not for jump problems. The underlying issue seems to be that `DiscreteFunction` didn't have fields to store the syms. This adds such fields in. Adding a reaction_network overload for `DiscreteProblem`s in DiffEqBiological will then allow us to get syms from reaction networks.
(I realize DiffEqBase is supposed to be updated infrequently, so if this is not worth adding in feel free to close. That said, I would really like it if I could get syms for jumps to allow auto labels in plot legends...)
=> add syms field for DiscreteFunctions

src/callbacks.jl, src/common_defaults.jl, src/init.jl
This allows proper handling of dual number time, along with allowing the user to do crazy things like change the adaptivity to be looser as time progresses
=> Add time to internalnorm and defaults

src/solutions/ode_solutions.jl
Currently the type of `sol(ode_prob, alg)` can not be inferred for algorithms in ODEInterfaceDiffEq and LSODA. Here's a (slightly complicated) example:
```julia
using ParameterizedFunctions, DiffEqBase
rober = @ode_def Rober begin
dy₁ = -k₁*y₁+k₃*y₂*y₃
dy₂ =  k₁*y₁-k₂*y₂^2-k₃*y₂*y₃
dy₃ =  k₂*y₂^2
end k₁ k₂ k₃
prob = ODEProblem(rober,[1.0;0.0;0.0],(0.0,1e11),(0.04,3e7,1e4))
using ODEInterfaceDiffEq
@code_warntype solve(prob,radau())
using LSODA
@code_warntype solve(prob,lsoda())
```
=> Fix type instability in build_solution

REQUIRE, docs/.gitignore, docs/Project.toml, docs/make.jl, docs/src/api/functions.md, docs/src/api/overview.md, docs/src/api/problems.md, docs/src/index.md, src/DiffEqBase.jl, src/diffeqfunction.jl, src/problems/discrete_problems.jl, src/problems/ode_problems.jl, src/problems/problem_traits.jl, src/problems/problem_utils.jl, src/problems/steady_state_problems.jl
This is a work in progress of documentation for the package's API, which isn't really covered in depth in DiffEqDocs.jl. I'm basically just adding docstrings to the important functions and types and then organizing references to them in some Documenter.jl files. So far I've covered most of the problem types and added stubs for the `AbstractDiffEqFunction` subtypes.
My goal here is to get enough of the documentation structure set up so that myself and others can continue filling in the docstrings in smaller increments.
=> API Documentation

src/init.jl, src/solutions/ode_solutions.jl
```julia
t = 0.5
for i in zip([1,2,3],t)
@show i
end
for i in zip([1,2,3],Iterators.repeated(t))
@show i
end
```
Demonstrates the without the repeats the norm gets truncated.
=> Fix extended norms with Iterators.repeated

REQUIRE, src/DiffEqBase.jl, src/init.jl, src/linear_nonlinear.jl
This default works with dense and sparse arrays, along with lazy operator definitions, out of the box.
Additionally, `linsolve = LinSolveGMRES()` now is a simple way to change to GMRES.
=> Add better default linsolve and easy GMRES

src/init.jl
This is still WIP since I can not get it to work, the code below causes a call to 
`convert(Float64, ::Particles{Float64,500})` which is not supported unless all particles are the same. Measurements.jl handles this convert the same, i.e., only allows it if the error is zero.
After having added the code in this PR, I have
```julia
julia> g
(500 Particles: 9.79 ± 0.02)
julia> DiffEqBase.ODE_DEFAULT_NORM(g,1.)
9.789991179929432
```
which indicates that the method is there and is producing a float as expected.
Any help appreciated :)
```julia
using MonteCarloMeasurements, OrdinaryDiffEq, Plots
using MonteCarloMeasurements: ±
g = 9.79 ± 0.02; # Gravitational constants
L = 1.00 ± 0.01; # Length of the pendulum
#Initial Conditions
u₀ = [0 ± 0, π / 60 ± 0.01] # Initial speed and initial angle …
```
=> Add MonteCarloMeasurements ODE_DEFAULT_NORM

src/init.jl
> Should it not remove the swarm when time is a swarm? I'm not sure how to think about that case here.
You are right. I think this PR makes a bit more sense.
Btw, many of the inits provide two methods, one which is slightly more specialized to `Array` instead of `AbstractArray`, but they otherwise do the same thing. Is there a reason for this or is it due to pattern matching and copy-paste when some previous packages have been inited? Example:
```julia
@inline function ODE_DEFAULT_NORM(u::AbstractArray{<:Measurements.Measurement,N},t) where {N}
sqrt(sum(x->ODE_DEFAULT_NORM(x[1],x[2]),zip((Measurements.value(x) for x in u),Iterators.repeated(t))) / length(u))
end
@inline function ODE_DEFAULT_NORM(u::Array{<:Measurements.Measurement,N},t) where {N} …
```
=> Update init for MonteCarloMeasurements

src/remake.jl
This is safe because `isinplace` is just looking at a type parameter
=> Pure the remaker

src/DiffEqBase.jl, src/callbacks.jl
An implementation of what was discussed in https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/331 and various Discourse posts. The idea is for the implementation to not be separate from the one used on ContinuousCallback, since that would promote code reuse and would allow ContinuousCallback to output things like a StaticVector and just work, which would be nice. However, dealing with the caches performantly seems to be an issue. Current issues are:
1. Breaking. Needs to add `previous_condition` and `callback_cache` to the integrator. This should be in the integrator and not in the callback in order to make it thread-safe. These should be allocated by the integrator to get the right element type, but the length needs to be given by the user when the callback is generated.
2. …
=> [WIP] VectorContinuousCallbacks

src/callbacks.jl
To make all the callback's temporary registers come in one place, this PR introduces a new structure `CallbackCache`. Changes required in OrdinaryDiffEq are also made in the PR JuliaDiffEq/OrdinaryDiffEq.jl#754. I am also trying to convert `next_sign` and `prev_sign` to `BitArray` but it seems that handling Floating Point error is tricky with this. Also we need to handle the case when condition at time steps is zero differently.
=> Adds CallbackCache

src/diffeqfunction.jl, test/diffeqfunction_tests.jl
Updated `(f::ODEFunction)()` to work with both in-place and out-of-place arguments, regardless of whether the wrapped function is in place or not. I'm not sure if calling out-of-place functions with the in-place style is a common use case, but I think the reverse definitely is (especially in interactive use). You can now use both types interchangeably without having to know the type parameter (although of course most applications that need optimal performance will still have to specialize).
You could probably easily extend this to the rest of the `DEFunction` subtypes by writing a macro for it.
=> ODEFunction accepts both in- and out-of-place styles in function call

src/nlsolve/type.jl, src/nlsolve/utils.jl
Seems like `κ` could be set to `1//100` instead of `nothing` by default, instead of setting it to `nothing`, checking for `nothing` during construction of the solver and its cache, and using `κ = 1//100` in that case. Feels a bit clearer to initialize it with `1//100` in the first place.
=> Set kappa to 1//100 instead of nothing

src/callbacks.jl
Fixes #249. This was not due to bad epsilon handling but was a bug. I forgot to add `event_idx` in one overload of `find_first_continuous_callback`. We really really need better callback tests. The recursive logic is weird and is prone to such errors.
=> CallbackSet fix

src/nlsolve/type.jl, src/nlsolve/utils.jl
In this we I have split the previously macros `oopnlsolve` and `iipnlsolve` into three parts -
1. Functions `iipnlsolve` and `oopnlsolve` which make the `nlsolver` using the cache arguments.
2. Functions `iip_generate_W` and `oop_generate_W` which make the `W` operator using cache arguments. I had to make a seperate function because `WOperator` is not defined inside DiffEqBase.
3. Macros `@getiipnlsolvefields` and `@getoopnlsolvefields` to get other fields used in algorithm caches of algos which used the previous macros.
Right now I get some instability issues, trying to resolve them.
=> Split NLSolve macros

src/callbacks.jl
Lets discuss about how we could actually better our epsilon handling. For those unfamiliar with this - when we hit a callback condition, i.e. `condition = 0` we want the exact time where the event occured. As there is nothing like "exact" in floating point, we calculate time to be the previous nearest floating point time. But when we do this, we are actually going back in time. This could cause infinite loop of events. Right now, we use derivate to calculate the condition in some near future and use the value as the `prev_condition`. But this had failed too (Ref #207).
In this PR, I have added two few tweaks - 
1. Fixed epsilon handling in negetive dt case - because `max` function actually calculates the smaller step (magnitude wise) of the two in case of negetive dt.
2. Buggy time …
=> Better epsilon handling in callbacks

src/init.jl, src/linear_nonlinear.jl
Auto-GPU linear solver usage. Allows for big linear solves to be GPU-accelerated even if the function is not amenable to GPU usage.
```julia
using OrdinaryDiffEq, ParameterizedFunctions
f = @ode_def Hires begin
dy1 = -1.71*y1 + 0.43*y2 + 8.32*y3 + 0.0007
dy2 = 1.71*y1 - 8.75*y2
dy3 = -10.03*y3 + 0.43*y4 + 0.035*y5
dy4 = 8.32*y2 + 1.71*y3 - 1.12*y4
dy5 = -1.745*y5 + 0.43*y6 + 0.43*y7
dy6 = -280.0*y6*y8 + 0.69*y4 + 1.71*y5 -
0.43*y6 + 0.69*y7
dy7 = 280.0*y6*y8 - 1.81*y7
dy8 = -280.0*y6*y8 + 1.81*y7
end
u0 = zeros(8)
u0[1] = 1
u0[8] = 0.0057
prob = ODEProblem(f,u0,(0.0,321.8122))
using CuArrays
sol = solve(prob,Rodas5(linsolve=DiffEqBase.LinSolveGPUFactorize()),
abstol=1/10^14,reltol=1/10^14)
```
=> add LinSolveGPUFactorize

src/callbacks.jl
Fixes #266. Actually the problem was that by default `event_last_error` is set to zero. When an event occurs at any timesteps, we do not update `event_last_error` (see [here](https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/callbacks.jl#L421)) So as long as the first non-timstep callback occurs, `event_last_error` is zero, hence the code wont enter [here](https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/callbacks.jl#L346) even if the `prev_condition` was zero. Therefore the callback got missed as we didn't calculate prev_sign in near future.
This code used to throw only a single ping, but is fixed in the branch -
```julia
using OrdinaryDiffEq
function f(u,p,t)
u
end
condition(u,t,integrator) = (t - 0.5)*(t - 0.6)
affect!(integrator) = println("ping")
cb = …
```
=> Fix missed callback

src/problems/dde_problems.jl
As mentioned in https://github.com/JuliaDiffEq/DiffEqProblemLibrary.jl/pull/39#issue-293098398, the order of the discontinuity at the initial time point for DDEs is a property of the problem (more precisely, the combination of `u0`, `t0`, and `h`). Hence I think it should be added to `DDEProblem` and not be provided as a keyword argument to `solve`.
=> Add order_discontinuity_t0 to DDEProblem

src/DiffEqBase.jl, src/diffeq_operator.jl, src/diffeqfunction.jl, src/nlsolve/utils.jl, src/utils.jl
This PR generalizes islinear to DiffEqFunctions. Moreover, I updated some outdated documentation of DiffEqOperators and replaced some calls of `A_mul_B!`.
The last two commits are not needed, but I think the name `du_cache` is a bit more appropriate and for consistency with Base and `islinear` `is_constant` could be replaced with `isconstant`.
=> Generalize islinear

src/nlsolve/newton.jl, src/nlsolve/type.jl, src/nlsolve/utils.jl
For this to be thread safe, we need to not edit any values from integrator. Right now we use `u` from integrator hence this is not thread safe. And having an extra `tmp_u` would hit all the other solvers. Should we have a new custom `ThreadedNLSolver`? This has 2 benefits, first - we don't play around the previously stable methods hence not breaking them. Secondly - we can have higher customization for such NLSolver, because in parallel methods, it's not necessary that you have 5 different `W` for 5 different threads.
=> [WIP] Make nlsolve thread safe

src/nlsolve/newton.jl
@kanav99 @YingboMa this is one that needs more looking into. @devmotion this could cause the differences we noticed in iip vs oop, and it was caught by an OrdinaryDiffEq test
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/test/integrators/integrator_interface_tests.jl#L6-L41
The issue was 
https://github.com/JuliaDiffEq/DiffEqBase.jl/compare/possible_fix?expand=1#diff-305950d2ce3e1263c689b30816f31933R173
The reason was because the `u` in the residuals was updating every step, so I changed it to just do it the thread-safe way. However, this raises a question: should we use the updated value of `u` in the residual each time? If we want to change it, we should change both iip and oop, not just one. If there's a bad iterate, using a higher `max` would reduce the effect of the …
=> fix failing OrdinaryDiffEq tests

src/nlsolve/utils.jl
These are small changes for resize to work, its broken right now as it assumes W and J are in alg cache. Ready for review @ChrisRackauckas
=> Resize changes for new nlsolve

src/linear_nonlinear.jl
```julia
using Test
using OrdinaryDiffEq
using SparseArrays
using LinearAlgebra
#https://github.com/JuliaDiffEq/SparseDiffTools.jl/blob/master/test/test_integration.jl
function f(dx,x,p,t)
for i in 2:length(x)-1
dx[i] = x[i-1] - 2x[i] + x[i+1]
end
dx[1] = -2x[1] + x[2]
dx[end] = x[end-1] - 2x[end]
nothing
end
function second_derivative_stencil(N)
A = zeros(N,N)
for i in 1:N, j in 1:N
(j-i==-1 || j-i==1) && (A[i,j]=1)
j-i==0 && (A[i,j]=-2)
end
A
end
function generate_sparsity_pattern(N::Integer)
dl = repeat([1.0],N-1)
du = repeat([1.0],N-1)
d = repeat([-2.0],N)
return Tridiagonal(dl,d,du)
end
jac_sp = sparse(generate_sparsity_pattern(10))
#jac = second_derivative_stencil(10)
colors = repeat(1:3,10)[1:10]
u0=[1.,2.,3,4,5,5,4,3,2,1]
tspan=(0.,10.)
odefun_sp= …
```
=> Always lu on SparseMatrixCSC

src/solve.jl, test/high_level_solve.jl
...so that `solve(prob; tspan=(t0, t1))` works.
=> Fix get_concrete_tspan

src/callbacks.jl
Seems like it has been broken for a very long time but masked by other test errors. And, e.g., Travis did not run for https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/318?!
=> Fix callback statistics

Project.toml, src/problems/analytical_problems.jl, src/problems/bvp_problems.jl, src/problems/dae_problems.jl, src/problems/dde_problems.jl, src/problems/discrete_problems.jl, src/problems/noise_problems.jl, src/problems/ode_problems.jl, src/problems/rode_problems.jl, src/problems/sde_problems.jl, src/problems/steady_state_problems.jl, src/remake.jl, src/solve.jl, test/remake_tests.jl
This is a multiple birds in one stone fix. In Pumas I realized it would be easier to use the Ensemble interface if I could add a tstop to the Ensemble. The fact that `callback` was in the problem always kind of annoyed me because it was an odd one out. Using `prob` remake stuff for parameter estimation couldn't handle possibly changing arguments like `d_discontinuities`. etc.
But if a `DEProblem` now captures the `kwargs`, then all of these are handled. In the higher level functions we just splat them in with the other `kwargs` and none of the solvers need to even explicitly handle this. `callback` is then automatically handled because it's a standard common interface argument.
=> Capture kwargs in problem construction

Project.toml, src/ensemble/basic_ensemble_solve.jl
Not all solve solutions are necessarily the same given the reduction and prob mechanism. This updates the way the concretization occurs to use the promotion system of `map` by simply using `map` itself.
=> Allow non-concrete ensemble

src/DiffEqBase.jl, src/fastpow.jl, test/fastpow.jl, test/runtests.jl
```julia
julia> using DiffEqBase: fastlog2
julia> function fastpow_bench(x, y)
l = 0f0
for i in 1:10_000_000
l += fastpow(x+i, y)
end
return l
end
fastpow_bench (generic function with 1 method)
julia> function pow_bench(x, y)
l = 0f0
for i in 1:10_000_000
l += ^(x+i, y)
end
return l
end
pow_bench (generic function with 1 method)
julia> pow_bench(1f0, 2f0)
3.3698455f20
julia> fastpow_bench(1f0, 2f0)
3.3697706f20
julia> @time pow_bench(1f0, 2f0)
0.180649 seconds (5 allocations: 176 bytes)
3.3698455f20
julia> @time fastpow_bench(1f0, 2f0)
0.091486 seconds (5 allocations: 176 bytes)
3.3697706f20
```
=> Add fast power function

src/operators/basic_operators.jl, src/operators/common_defaults.jl, src/operators/diffeq_operator.jl, test/basic_operators_interface.jl
https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/835254896f9b97669edfe3a28362ed8978b6c0e9/src/operators/diffeq_operator.jl#L126 has been there for a while. This PR renames `is_constant` to `isconstant`. Also, it directs `islinear` to `isconstant`.
=> `is_constant` -> `isconstant`

test/downstream/ensemble.jl
Adds a test for https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/241
=> add batch_size test

test/gpu/simple_gpu.jl
Apparently one of the GPU tests is not broken anymore: https://gitlab.com/juliadiffeq/OrdinaryDiffEq-jl/-/jobs/351952429
=> GPU test not broken anymore

src/diffeqfunction.jl
Not only is encoding the `jvp` into the Jacobian type a little odd, it also makes it fairly hard to document and define `vjp`s, and then use them in sensitivity analysis. So I was thinking that we might as well leave `jac_prototype` just for the Jacobian type definition, and then define `jvp` separately. This removes the requirement of having it as a `DiffEqOperator` and all of that stuff that seems to be getting in the way. Just a function `jvp(out,v,u,p,t) = f'(u)*v` and `vjp(out,v,u,p,t) = v'*f'(u)` for things like ModelingToolkit to generate and for DiffEqSensitivity to use. 
As for `Wvp`, I think that we can still generate that `WOperator`, which just uses a `jvp` call in there. The mass matrix would then still have to be handled separately, but I don't see a major issue with that? …
=> add jvp,vjp

Project.toml, src/DiffEqBase.jl, src/zygote.jl
@YingboMa I realized that this would make it fairly clean and easy for the DiffEqSensitivity implementations, since now it doesn't have to have a branch to handle the existence of a vjp but is just built into the `autojacvec` implementation once it's Zygote.
@oxinabox this commented part is what I mean though, where in the sensitivity analysis implementations I want to calculate `df/du *v`for `f(u,p,t)`, but there doesn't seem an idea for that Jacobian-vector product in ChainRules. It's not issue though an easy to work around, but food for thought.
=> add Zygote and ChainRules adjoint rules to the ODEFunction

src/problems/problem_utils.jl
Master
```julia
julia> Zygote.gradient(x->sum(ODEProblem{true}((u,p,t)->u, x, (0, 1.0)).u0), ones(5))
ERROR: MethodError: no method matching length(::Nothing)
Closest candidates are:
length(::Core.SimpleVector) at essentials.jl:593
length(::Base.MethodList) at reflection.jl:849
length(::Core.MethodTable) at reflection.jl:923
...
Stacktrace:
[1] unzip(::Tuple{Nothing,Nothing}) at /home/scheme/.julia/packages/Zygote/fw4Oc/src/lib/array.jl:125
[2] (::Zygote.var"#1110#1114"{Tuple{Zygote.var"#45#64",Zygote.var"#45#64"}})(::Tuple{Nothing,Nothing}) at /home/scheme/.julia/packages/Zygote/fw4Oc/src/lib/array.jl:137
[3] (::Zygote.var"#2878#back#1116"{Zygote.var"#1110#1114"{Tuple{Zygote.var"#45#64",Zygote.var"#45#64"}}})(::Tuple{Nothing,Nothing}) at …
```
=> Simplify `promote_tspan`

src/solutions/solution_interface.jl
Resolves #425 - Allows for `theme()` to control solution plotting defaults.
=> Closes #425: Remove linewidth specification from plot recipe

Project.toml, src/init.jl, test/norm.jl, test/runtests.jl
We want the tests in https://github.com/JuliaDiffEq/DiffEqBase.jl/compare/myb/dual_norm?expand=1#diff-b7439ee44628e4b8309362bed2cb652b to pass to make sure that the time adaptivity hits the same points.
=> Fix the default norm on duals

Project.toml, src/utils.jl, test/utils.jl
Fix CI failures in https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/1045
=> Add missing method for timedepentdtmin

src/problems/problem_utils.jl, test/high_level_solve.jl
We should either try to automatically convert or throw a nice error message. I think this is a good middle ground. Comments @yingboma?
=> better handling of array tspan

src/solve.jl
That looks wrong but was not captured by any tests.
=> Fix use of maybe_with_logger

src/callbacks.jl, src/init.jl, src/solve.jl
We know these are common pitfalls: here's a system to work around it. For now it won't be documented so we can keep improving it.
=> promote u0 and tspan to auto-fix autodiff bugs

src/callbacks.jl, src/init.jl, test/bisection_tests.jl, test/downstream/ode_event_tests.jl
The new `find_bracket` feature doesn't work either, in fact it brings an unexpected issue. I think we should think of a new approach to fix this floating point issue.
1. In case of repeated event, currently we check using derivative. If value of condition is small enough and is increasing, we say that sign is +ve on the left hand (similar for decreasing ). But when we find the callback time, we use actual value of condition at some point ahead until it switches sign. I think this is something wrong, for both detection and time calculation we should do the same. Otherwise such errors are bound to happen.
2. We also do need a `OnceContinuousCallback` that only runs once. or maybe a good way to switch off the callback. A part of code can be simplified if we make a way to switch off the …
=> Try to fix callbacks

src/solutions/solution_interface.jl
- automatically convert \_+ to non-Unicode to make it easier for backends to support module syntax
- check for integers first, then convert anything else to a symbol. This makes the MTK variable automatically supported.
=> Improve plotting for ModelingToolkit changes

src/callbacks.jl, src/init.jl
Fixes https://github.com/SciML/DifferentialEquations.jl/issues/590
The condition function in the issue was such that value of condition at `bottom_t` was -700 and `nextfloat(bottom_t)` was 2000 so our bisection function would have returned `bottom_t`.  There's nothing much we can do in such condition functions, but throwing an error just because there isn't much precision in a very very specific case wasn't good either.
So I made a kwarg which tells if the bisection function can return left most value or not. 
@ChrisRackauckas @BeastyBlacksmith
=> Fix bisection to make it not return tprev

src/callbacks.jl
Very small changes to code and removed that error.
Scripts tested on:
```julia
using OrdinaryDiffEq, Test
lastt = 0.0
f = function (du,u,p,t)
du[1] = u[2]
du[2] = -p[1]
end
function condition(u,t,integrator) # Event when event_f(u,t) == 0
u[1]
end
function affect!(integrator)
@test integrator.u[1] >= 0
global lastt
println("bounce at interval $(integrator.t - lastt)")
lastt = integrator.t
integrator.u[2] = -integrator.u[2]
end
cb2 = ContinuousCallback(condition,affect!)
tspan = (0.0,Float64(Inf))
u0 = [50000.0,0.0]
p = 9.8
prob = ODEProblem(f,u0,tspan,p)
integ = init(prob,Tsit5(),callback=cb2,maxiters=Inf,progress=true)
solve!(inter)
```
This one makes the ball go negative (as dt goes very big) on master. Works fine on this PR(watch out, tspan is infinite long so the script wont stop). …
=> Callback Fix: Allowing 0 `cb_time`

Project.toml, src/diffeqfastbc.jl
```julia
julia> using StaticArrays
julia> using DiffEqBase: @..
[ Info: Precompiling DiffEqBase [2b5f629d-d688-5b77-993f-72d75c75574e]
julia> a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z = [@MArray(rand(10, 2)) for i in 1:26];
julia> function foo9(a, b, c, d, e, f, g, h, i)
@.. a = b + 0.1 * (0.2c + 0.3d + 0.4e + 0.5f + 0.6g + 0.6h + 0.6i)
nothing
end
foo9 (generic function with 1 method)
julia> function foo9_1(a, b, c, d, e, f, g, h, i)
@. a = b + 0.1 * (0.2c + 0.3d + 0.4e + 0.5f + 0.6g + 0.6h + 0.6i)
nothing
end
foo9_1 (generic function with 1 method)
julia> using BenchmarkTools
julia> @time foo9(a, b, c, d, e, f, g, h, i) # @..
0.277952 seconds (1.76 M allocations: 79.222 MiB, 10.08% gc time)
julia> @time foo9_1(a, b, c, d, e, f, g, h, i) # @.
0.975069 …
```
=> Fix @.. on MArrays

Project.toml, src/diffeqfunction.jl
You can use a colorvec even when a dense Jacobian is faster for the lu-factorization
=> separate sparsity and jac_prototype types

src/init.jl, test/norm.jl
This changes the norms on dual numbers to include the dual portions. This means that the solution to the ODE under automatic differentiation is not necessarily the same as without. However, https://github.com/SciML/DiffEqSensitivity.jl/issues/273 nicely highlights some edge cases that show that this is somewhat necessary. In that case, the integrator has zero error, and so time steps are unaffected by tolerances which causes gradients to explode since they are not tolerance controlled. This change adds them to the summation and the length, making the solution by dual numbers equivalent to the result of forward sensitivity analysis under the default norm.
@yingboma what do you think?
@pkofod you might want to test this with Pumas. It should give it some more robustness.
Fixes …
=> make dual norms include the dual terms

src/common_defaults.jl
This results in dramatic speedups on complex numbers, and since this is only used in error norm heuristics, it doesn't need to be very accurate anyways.
=> Use fastmath on abs

src/diffeqfunction.jl, test/norm.jl
You know how sometimes you later think that some idea was a really really bad idea? Yes, this was one of them. "It's a pair of ODEs, so it's a pair of mass matrices!". Yeah, but that breaks all implicit solver fallbacks, and even when implicit methods specialized to second order ODEs exist, mass_matrix=I will still work as the special case to catch, so it's just better...
Anyways, it didn't matter until last week when ArrayPartition suddenly became compatible with all implicit solvers, except for the fact that it would fail because the mass matrix was by default a tuple. So, let's fix this and yay, 2nd order ODEs are now better.
Fixes https://github.com/SciML/DiffEqBase.jl/pull/536
=> mass matrix I for DynamicalODEFunction

Project.toml, src/operators/basic_operators.jl
This is also related to https://github.com/SciML/OrdinaryDiffEq.jl/blob/91175ba20bf3e604f1b3150ec7a1ac49083f6487/src/derivative_utils.jl#L169-L170
It seems that we don't have the ability to express when we can reasonably "concretize" the operator and ask for the type of the concretized operator.
=> Make DiffEqArrayOperator ExponentialUtilities.jl compatible

src/callbacks.jl, test/downstream/bigfloat_events.jl, test/runtests.jl
`===` is not appropriate unless it's determined by a constant, and it fails on any mutable number (bigfloats). Also the default maxiters was made higher to handle default bigfloat precision
Fixes https://github.com/SciML/DifferentialEquations.jl/issues/653
=> make bisection compatible with bigfloat

src/callbacks.jl
In using VectorContinuousCallback in my code I came across several bugs, leading to exceptions, which I think I've fixed here.
1. The check `integrator.vector_event_last_time == event_idx` compared an Int to a Vector{Int} so it would always be false. I think it should be `idx` instead of `event_idx`.
2. The `diff_t` used in the nudging of the bottom t to find a different sign for bottom and top was using machine epsilon of the type, not the actual time. In my particular case, t was very large causing this to fail.
3. The check between `find_callback_time` and `bisection` was inconsistent. The nudger in `find_callback_time` was happy with a zero value for bottom_t, but `bisection` wanted a non-zero value.
I wanted to write some tests for this but ran out of time and figured that these are …
=> Callback bug fixes

src/callbacks.jl, test/downstream/ode_event_tests.jl
Fix for https://github.com/SciML/DifferentialEquations.jl/issues/662
Reproduced here for quick reference:
---
When trying to forward diff through an ODE with a `VectorContinuousCallback`, I’m getting:
```
ERROR: MethodError: no method matching has_continuous_callback(::DiffEqBase.VectorContinuousCallback{...})
```
Tracing through a little more, I find that `has_continuous_callback()` is called if `ForwardDiff` is loaded, but they are only defined for:
```
has_continuous_callback(cb::DiscreteCallback) = false
has_continuous_callback(cb::ContinuousCallback) = true
has_continuous_callback(cb::CallbackSet) = !isempty(cb.continuous_callbacks)
has_continuous_callback(cb::Nothing) = false
```
and not for `VectorContinuousCallback`.
=> Add missing has_continuous_callback(::VectorContinuousCallback) method

src/callbacks.jl, src/init.jl
In following up my inference issues identified in #574, I think I found another couple of bugs.
1. The `prevfloat_tdir` variable in `bisection(...)` doesn't seem to be expanded into its two possibilities by the compiler, so the return value of the function was an `Any`. I "fixed" this by putting it as an argument to the function with a default. This feels like a dirty hack to me... is there a better way to get the same result?
2. One of the `CallbackCache` constructors (which is used only for `VectorContinuousCallback`) was setting the parameters to be `Array{Float64}` without a dimension, so it would appear as `Array{Float64,N}` in my integrator object. I don't think Array was the intent anyway, so I changed it to be the same as the other constructor, which is `typeof(tmp_condition)`.
=> Fixed inference issues in bisection and CallbackCache

src/problems/dae_problems.jl, test/problem_creation_tests.jl
Require uniform dimensionality between u0, du0, and differential_vars. Should prevent undefined memory access in
Sundials.jl when invalid inputs are passed.
Fixes #581
=> Guard against invalid DAEProblems

src/operators/diffeq_operator.jl, test/affine_operators_tests.jl
This PR fixes (I hope) calls of the type `L(u,p,t)` for `L::AffineDiffEqOperator`.
I think there was a number of mistakes in this function (e.g., the spurious double parentheses in `sum((...))`).
Also, I thought that once `tmp` is created with the `A*u` terms, we could add the `B`s to it inplace. (So I renamed `tmp` as `du` to clarify that, but maybe that's not good practice?)
=> Fix L(u,p,t) call for AffineDiffEqOperator

src/diffeqfunction.jl
For `SDEFunction` and `SDDEFunction`, the type parameters `S` and `GG` are out of order with their corresponding fields `ggprime` and `syms`.
=> Match type params with their corresponding fields

src/problems/basic_problems.jl
We don't need a separate field for it since it can just be obtained from the length of the constraint bounds
=> Remove num_cons field from OptimizationFunction

src/integrator_interface.jl
There was a stray newline between the docstring and the function which seems to have caused the docstring to not be associated with the function. This means that the docs site can't find the docstring and shows an error instead.
=> Fix docstring for deleteat!

src/common_defaults.jl, test/ode_default_norm.jl, test/runtests.jl
This ensures that it does not fail for ArrayPartitions of Numbers. Will be helpful for fixing https://github.com/SciML/OrdinaryDiffEq.jl/issues/1308
Also, added ode_default_norm tests to `runtests.jl`. Previously missing.
=> Extended recursive_length to operate on Number type

src/common_defaults.jl, test/ode_default_unstable_check.jl
There is a problem with the current implementation of `ODE_DEFAULT_UNSTABLE_CHECK` in common_defaults.jl.
- First of all, it does not work well with a `Vector` of `StaticArray`s: it tries to call `isnan` on `StaticArray` and this is not defined.
- Analogously, there is a problem with sophisticated variants of `ArrayPartition`: if `ArrayPartition` contains another `ArrayPartition`, it will try to call `isnan` on `ArrayPartition` which is, again, not defined. A `Vector` of `StaticArray`s inside an `ArrayPartition` breaks things as well.
This PR fixes these problems. The function `ODE_DEFAULT_UNSTABLE_CHECK` now calles another function, `NAN_CHECK`, which handles `isnan` for the nested subarrays recursively. Basically, `NAN_CHECK` defines the appropriate dispatch of `isnan` for various array …
=> Fixes ODE_DEFAULT_UNSTABLE_CHECK on sophisticated nested arrays.

src/integrator_interface.jl, test/integrator_tests.jl
By default these implementations return `Base.SizeUnknown()` since in general we do not know in advance how many steps there will be before an iterator finishes.
Without these new implementations a call to `Base.collect` e.g. on `IntegratorTuples` fails with `ERROR: MethodError: no method matching length` since by default `collect` assumes that all iterators implement `length` (see https://docs.julialang.org/en/v1/manual/interfaces/#man-interface-iteration ).
=> Implement Base.IteratorSize for integrator iterators

Project.toml, src/linear_nonlinear.jl
Fix https://github.com/SciML/OrdinaryDiffEq.jl/issues/1316
I will post a change to disable the non-adaptive forwarding on the OrdinaryDiffEq side later.
=> Make linear iterative solver more robust

src/callbacks.jl
This is a simple fix to the zero callback in https://discourse.julialang.org/t/diffeq-tolerances-on-continuouscallbacks/53181
=> Handle callback dt at t=0 separately

src/solve.jl
Add support for declaring NonlinearProblem. Otherwise, `tspan` argument was missing error was showing.
@ChrisRackauckas, please review.
=> Add get_concrete_problem for NonlinearProblem

src/calculate_residuals.jl
```julia
using DiffEqBase
out, ũ, u₀, u₁ = [rand(100,100) for i in 1:4];
α, ρ, internalnorm, t = 1e-4, 1e-6, DiffEqBase.ODE_DEFAULT_NORM, 0.1;
DiffEqBase.calculate_residuals!(out, ũ, u₀, u₁, α, ρ, internalnorm, t);
using BenchmarkTools
@btime DiffEqBase.calculate_residuals!($out, $ũ, $u₀, $u₁, $α, $ρ, $internalnorm, $t);
```
gives
```julia
julia> @btime DiffEqBase.calculate_residuals!($out, $ũ, $u₀, $u₁, $α, $ρ, $internalnorm, $t); # fastmath
11.188 μs (0 allocations: 0 bytes)
julia> @btime DiffEqBase.calculate_residuals!($out, $ũ, $u₀, $u₁, $α, $ρ, $internalnorm, $t); # master
20.854 μs (0 allocations: 0 bytes)
```
=> Add fastmath on scalar `calculate_residuals`

src/fastpow.jl
Benchmarks, before:
```julia
julia> using FastBroadcast, DiffEqBase, BenchmarkTools
julia> x = randn(Float32, 256); y = similar(x);
julia> @benchmark @.. $y = Base.Math.exp_impl_fast($x,Val(2)) # inlined base broadcast
BenchmarkTools.Trial:
memory estimate:  0 bytes
allocs estimate:  0
--------------
minimum time:     179.794 ns (0.00% GC)
median time:      180.200 ns (0.00% GC)
mean time:        180.345 ns (0.00% GC)
maximum time:     230.781 ns (0.00% GC)
--------------
samples:          10000
evals/sample:     700
julia> @benchmark @.. $y = DiffEqBase._exp2($x)
BenchmarkTools.Trial:
memory estimate:  0 bytes
allocs estimate:  0
--------------
minimum time:     108.322 ns (0.00% GC)
median time:      108.691 ns (0.00% GC)
mean time:        108.841 ns (0.00% GC)
maximum time:     164.939 …
```
=> Faster SIMD _exp2

src/common_defaults.jl, test/ode_default_norm.jl
I’ve added the change proposed in #664 plus a test that fails without that fix. The `mapreduce_empty` implementation mirrors [what is done for `abs2` in `Base`](https://github.com/JuliaLang/julia/blob/6aaedecc447e3d8226d5027fb13d0c3cbfbfea2a/base/reduce.jl#L345).
=> Fix ODE_DEFAULT_NORM for empty arrays (fixes #664)

src/callbacks.jl, test/downstream/event_detection_tests.jl
Sometimes simple is better. Instead of using a derivative estimate, now we just check at t + dt * repeat_nudge to avoid repeated zeros, with a default to 1//100 which seems to be a nice balance between numerical stability and keeping most of the interval still an eventful zone. 
Fixes https://github.com/SciML/DifferentialEquations.jl/issues/758
Fixes SciML/DifferentialEquations.jl#647
Fixes SciML/DifferentialEquations.jl#724
Fixes SciML/DifferentialEquations.jl#601
Fixes SciML/DifferentialEquations.jl#642
Fixes https://github.com/SciML/DiffEqBase.jl/issues/599
=> Use a nudge factor to remove repeats

src/solve.jl
Part of https://github.com/SciML/SciMLBase.jl/issues/69
And needs to be done with https://github.com/SciML/DiffEqSensitivity.jl/pull/428
But currently getting:
```julia
using DiffEqSensitivity, OrdinaryDiffEq, Zygote
function fiip(du,u,p,t)
du[1] = dx = p[1]*u[1] - p[2]*u[1]*u[2]
du[2] = dy = -p[3]*u[2] + p[4]*u[1]*u[2]
end
function foop(u,p,t)
dx = p[1]*u[1] - p[2]*u[1]*u[2]
dy = -p[3]*u[2] + p[4]*u[1]*u[2]
[dx,dy]
end
p = [1.5,1.0,3.0,1.0]; u0 = [1.0;1.0]
prob = ODEProblem(fiip,u0,(0.0,10.0),p)
du01,dp1 = Zygote.gradient((u0,p)->sum(solve(prob,Tsit5(),u0=u0,p=p,abstol=1e-14,
reltol=1e-14,saveat=0.1,sensealg=QuadratureAdjoint())),u0,p)
```
```julia
ArgumentError: tuple must be non-empty
first(#unused#::Tuple{}) at tuple.jl:134
_unapply(t::Nothing, xs::Tuple{}) at lib.jl:163 …
```
=> replace main Zygote.adjoints with ChainRules rrules

src/common_defaults.jl
I was using a `DEDataArray` that contained an `ArrayPartition` with a complex and a real part in an ODEProblem. I noticed during profiling that the error checking was taking a long time. This was due to the type-unstable iteration of the `ArrayPartition`. However, by adding an extra dispatch for the NAN_CHECK it is possible to avoid this. This seems to give a good speedup without any negatives.
```julia
using DiffEqBase
using RecursiveArrayTools
using BenchmarkTools
mutable struct MyDataArray{T}  <: DEDataArray{T,1}
x::ArrayPartition{Complex{T}, Tuple{Vector{T},Vector{Complex{T}}}}
state::Int
end
partition = ArrayPartition(rand(10), rand(ComplexF64, 10))
data_array = MyDataArray(partition, 1)
new_NAN_CHECK(x::DiffEqBase.DEDataArray) = any(DiffEqBase.NAN_CHECK, x.x)
```
```julia
julia> …
```
=> Add new NAN_CHECK for DEDataArray

src/linear_nonlinear.jl
Generalize the linear solver interface by allowing cache resizing, which right now just does cache invalidation.
=> Define resize! on factorization methods

src/chainrules.jl, src/solve.jl, test/downstream/ensemble_ad.jl
This is the correct way to fix https://github.com/SciML/DiffEqFlux.jl/issues/595, though it will need a followup in DiffEqSensitivity since there was some hardcoded forwarding of specific arguments in there before. Now, none of the concrete_solve dispatches need to handle any of the cases, which will make it much more sane and ensure that the adjoint forward pass always matches the regular forward pass.
=> Handle all prob.kwargs at the interface level

src/DiffEqBase.jl, src/common_defaults.jl, src/linear_nonlinear.jl, src/precompile.jl, src/solve.jl
```julia
using OrdinaryDiffEq, SnoopCompile
function lorenz(du,u,p,t)
du[1] = 10.0(u[2]-u[1])
du[2] = u[1]*(28.0-u[3]) - u[2]
du[3] = u[1]*u[2] - (8/3)*u[3]
end
u0 = [1.0;0.0;0.0]
tspan = (0.0,100.0)
prob = ODEProblem(lorenz,u0,tspan)
alg = Rodas5()
tinf = @snoopi_deep solve(prob,alg)
```
@timholy this should be the right method:
```julia
_linsolve = DefaultLinSolve()
_testf(du,u,p,t) = du .= u
b = rand(1); x = rand(1)
_linsolve(Val{:init},ODEFunction(_testf),b)
A = rand(1,1)
_linsolve(x,A,b,true)
@which _linsolve(x,A,b,true)
```
=> attempt to precompile linsolve

src/callbacks.jl, src/init.jl, test/downstream/ode_event_tests.jl
Works towards https://discourse.julialang.org/t/significant-allocations-with-callbacks-tsit5/66467
=> Non-allocating VectorContinuousCallbacks and better typing

src/solve.jl
Current version allocates memory by creating a vector instead of a tuple so that the subsequent named tuple can be type unstable. I switched to creating a tuple, instead.
=> Type stable NamedTuple creation

src/linear_nonlinear.jl
```julia
using OrdinaryDiffEq, SnoopCompile, ForwardDiff
lorenz = (du,u,p,t) -> begin
du[1] = 10.0(u[2]-u[1])
du[2] = u[1]*(28.0-u[3]) - u[2]
du[3] = u[1]*u[2] - (8/3)*u[3]
end
u0 = [1.0;0.0;0.0]; tspan = (0.0,100.0);
prob = ODEProblem(lorenz,u0,tspan); alg = Rodas5();
tinf = @snoopi_deep ForwardDiff.gradient(u0 -> sum(solve(ODEProblem(lorenz,u0,tspan),alg)), u0)
```
Before:
```julia
InferenceTimingNode: 1.720146/12.692469 on Core.Compiler.Timings.ROOT() with 32 direct children
```
After:
```julia
InferenceTimingNode: 1.243689/4.828318 on Core.Compiler.Timings.ROOT() with 33 direct children
```
=> Avoid RecursiveFactorization except on simple number types

Project.toml
This PR backports support for ChainRulesCore 1.0 to DiffEqBase 6.59. The PR is made against the `6_59_backport` branch. If tests pass, this can be merged and a new release 6.59.1 can be made off of the backport branch.
=> Backport ChainRulesCore 1.0 support to 6.59

src/common_defaults.jl
Suggestion from https://github.com/SciML/DiffEqBase.jl/issues/664 . Requires v1.6 and we're in the future.
=> Remove mapreduce_empty

src/common_defaults.jl
This crates a short path improving performance by avoiding redundant computations.
=> improve `recursive_length` for arrays of static arrays

src/DiffEqBase.jl, src/solve.jl, test/downstream/ensemble.jl, test/downstream/kwarg_warn.jl, test/runtests.jl
This has been a long time coming. The DiffEq, and more generally, SciML interfaces have a set of common keyword arguments, but it's been fairly difficult to truly enforce. The main reason is because the keyword arguments are `kwargs...` splatted down to the solvers, and then it's the solver's job to handle it. However, with so many different problem types and everything, there has been a changing list of keyword arguments over time, and some solvers re-splat the keyword arguments because of how many different kwargs they can end up getting if, for example, one wasn't using controls for parameter estimation or something.
In pre-1.0 Julia, there wasn't a good fix for downstream users as if you would error on some keyword arguments, they would have to sanitize their list before dropping to …
=> Add a common kwarg warning system

Project.toml, src/solve.jl, test/downstream/solve_error_handling.jl, test/runtests.jl
Fixes the issue discussed in https://discourse.julialang.org/t/blog-post-about-my-experiences-with-julia/79976/84. A better fix is for this to be addressed at the Julia level, i.e. https://github.com/JuliaLang/julia/issues/45086, though we might as well catch and throw before the solve to keep the stacktrace small.
=> Check and throw on incompatible initial conditions

src/solve.jl, test/downstream/solve_error_handling.jl
```julia
using Sundials, LinearAlgebra
function dfdt!(du, u, p, t)
du[1] = u[8] / 1.072
du[2] = u[9] / 0.2638
du[3] = u[10] / 1.682
du[4] = u[11] / 0.8365
du[5] = u[12] / 0.7265
du[6] = u[2] / 1.304
du[7] = u[4] / 0.8586
du[8] = u[10] + u[11] + u[7] - u[9] - u[6]
du[9] = u[1] - u[3] - u[2]
du[10] = u[3] - u[5] - u[4]
du[11] = u[8] + u[9] + u[6] - 1.0 + u[1]
du[12] = u[11] + u[7] - u[12] - u[5]
return nothing
end
u0 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
M = Diagonal([1.,1.,1.,1.,1.,1.,1.,0.,0.,0.,0.,0.])
t1 = [0.0:0.1:10.0;]
tspan = (t1[1], last(t1))
f = ODEFunction(dfdt!, mass_matrix=M)
prob = ODEProblem(f, u0, tspan)
sol = solve(prob, IDA())
```
Old error message: https://discourse.julialang.org/t/modelingtoolkit-vs-plain-differentialequations/81322/10?u=chrisrack …
=> Better error message for incompatible solver + problem pairings

src/solve.jl, test/downstream/solve_error_handling.jl
Just another step on the quest to make things just a bit nicer to use.
=> Throw a high level interpretable error for non-concrete eltype `u0`

src/solve.jl
I don't really care about the styling so I'm happy to remove it, but mainly I can't think of a reason why you wouldn't want the warning to show the incorrect kwargs. Also a few readability improvements. 
I didn't want to interpolate into the warning message since it'd have to reallocate the string, so I just print after the warning
```julia 
julia> sol = solve(prob_ode_lotkavoltera, Tsit5())
┌ Warning: Unrecognized keyword arguments found. Future versions will error.
│ The only allowed keyword arguments to `solve` are: 
│ (:dense, :saveat, :save_idxs, :tstops, :d_discontinuities, :save_everystep, :save_on, :save_start, :save_end, :initialize_save, :adaptive, :abstol, :reltol, :dt, :dtmax, :dtmin, :force_dtmin, :internalnorm, :controller, :gamma, :beta1, :beta2, :qmax, :qmin, :qsteady_min, …
```
=> always print the unrecognized kwargs

src/solve.jl
Changes `Tsti5()` to `Tsit5()`. I also added a link to the available solvers to be consistent with `NO_DEFAULT_ALGORITHM_MESSAGE`, in case you think that can be useful.
=> Typo in recommended algorithm Tsti5

src/chainrules.jl
Fixes the remaining error in the pullback of https://github.com/SciML/RecursiveArrayTools.jl/pull/221.
The MWE
```julia
function loss(u0, p)
_u0 = ArrayPartition(u0)
_prob = ODEProblem(fiip, _u0, (0.0, 10.0), p)
_sol = solve(_prob, Tsit5(), abstol=1e-14, reltol=1e-14, saveat=0.1)
sum(_sol)
end
```
from https://github.com/SciML/SciMLSensitivity.jl/issues/689 then works. However, it does not see this rrule definition for `remake` https://github.com/SciML/SciMLBase.jl/blob/0d55f56283fda3b6accb12fb282531447bdabe7c/src/remake.jl#L77 yet... Any ideas how to generalize it to account for the isinplace?
=> Add rrule for ODE and SDEProblem constructors

.github/workflows/Downstream.yml, src/common_defaults.jl
This PR is purely motivated by aesthetics, not benchmarks.
When looking at assembly of an experimental perform_step! function, I thought it'd be prettier without the error check and call to complex domain error.
=> @fastmath sqrt for ODE_DEFAULT_NORM

src/chainrules.jl
Unbound type parameters often cause performance issues and run time dispatch.
Issue found using https://github.com/JuliaLang/julia/pull/46608
=> remove unbound type parameter

src/forwarddiff.jl, test/forwarddiff_dual_detection.jl
Since https://github.com/JuliaLang/julia/pull/39448, `getproperty` has been deprecated in favor of `getfield`.
=> fix deprecated call

src/common_defaults.jl, test/ode_default_norm.jl
fixes problem introduced in https://github.com/SciML/DiffEqBase.jl/pull/697.
=> fix ODE_DEFAULT_NORM for empty vectors

Project.toml, ext/DistributionsExt.jl, src/DiffEqBase.jl, src/solve.jl
On 1.9, this saves roughly .5 seconds. We also should do this for chainrules, but I'll leave that for another PR.
Before
```
julia> @time @eval using DiffEqBase
1.914418 seconds (6.02 M allocations: 432.638 MiB, 6.05% gc time, 16.83% compilation time: <1% of which was recompilation)
```
After
```
julia> @time @eval using DiffEqBase
1.516961 seconds (4.86 M allocations: 365.564 MiB, 5.58% gc time, 18.51% compilation time: <1% of which was recompilation)
```
=> make Distributions a weak dependency

src/forwarddiff.jl, test/downstream/complex_number_ad.jl, test/forwarddiff_dual_detection.jl, test/runtests.jl
see issue https://github.com/SciML/DiffEqBase.jl/issues/858
=> Passthrough AD in ode with complex numbers

ext/GeneralizedGeneratedExt.jl, ext/MonteCarloMeasurementsExt.jl, src/DiffEqBase.jl, src/common_defaults.jl, src/init.jl, test/gpu/simple_gpu.jl
Using Static Arrays in `ODE_DEFAULT_NORM` wasn't hitting the correct dispatch:
```
using StaticArrays, DiffEqBase, Cthulhu
tmp = @SArray rand(10)
@descend DiffEqBase.ODE_DEFAULT_NORM(tmp, 1.0)
```
```
ODE_DEFAULT_NORM(u::AbstractArray, t) in DiffEqBase at /home/gridsan/utkarsh/.julia/dev/DiffEqBase/src/common_defaults.jl:37
∘ ─ %0 = invoke ODE_DEFAULT_NORM(::SVector{100, Float64},::Float64)::Float64
38 1 ─ %1 = invoke Base.var"#mapreduce##kw"()($(QuoteNode((init = 0.0,)))::NamedTuple{(:init,), Tuple{Float64}}, DiffEqBase.mapreduce::typeof(mapreduce), DiffEqBase.UNITLESS_ABS2::Function, DiffEqBase.abs2_and_sum::Function, u::SVector{100, Float64})::Float64
```
Apparently, this caused problems with using the method in https://github.com/SciML/DiffEqGPU.jl
```
using DiffEqBase, CUDA, …
```
=> Fix ODE_DEFAULT_NORM for Static Arrays

src/DiffEqBase.jl, src/solve.jl, test/downstream/null_de.jl
Take 2 of https://github.com/SciML/OrdinaryDiffEq.jl/pull/1818 This time it works with external solvers. @ChrisRackauckas how should I add a test for this? I can't `init` a problem within DiffEqBase since none of the algs are defined.
=> allow initing and solving with u0=nothing

src/solve.jl
The `NullODEIntegrator` was missing a few pieces needed to satisfy the implicit contract required to index into it with observables.  This closes the gap, storing the problem's `.f` and `.p` fields.
It might make sense to eventually re-work these APIs to use accessor functions such as `get_func()` or `get_parameterization()`, which can then flexibly thread through to `.prob.f` or similar, although I understand such a rework is not exactly appealing work.
=> Add function and parameterization properties to `NullODEIntegrator`

src/solve.jl, test/forwarddiff_dual_detection.jl
This is a completely harmless change, just the tests are for inference of everything and the inference of one item seems to have changed.
=> fix dual detection inference specification for v1.9

Project.toml, src/DiffEqBase.jl, src/termination_conditions.jl
The initial implementation was based on the version in DEQs.jl. But DEQs.jl stored the solver history, which means returning just the best index was good enough. But to generically handle NonlinearSolve.jl, we will also have to store the state.
See https://github.com/avik-pal/BatchedNonlinearSolve.jl/blob/5ff8656e82348e587e2a7645b76c9cf6608e3712/src/raphson.jl#L36 where I am testing out some aspects before moving stuff to NonlinearSolve.
=> Add a result with state stored for better handling of non linear solvers

src/DiffEqBase.jl, src/callbacks.jl, src/internal_falsi.jl, src/internal_itp.jl, test/internal_rootfinder.jl, test/runtests.jl
This PR interleaves the bisection and the regula falsi iterations to be able to handle tricky callbacks without going into maxiters. See discussion in #916
=> Improve robustness of the InternalFalsi solver

src/internal_falsi.jl, src/internal_itp.jl, test/internal_rootfinder.jl
The new event time rootfinder fails with reverse-time problems; this PR fixes it.
=> Fix reversed time callback detection failure

src/callbacks.jl, test/callbacks.jl
As mentioned in SciML/DifferentialEquations.jl#971, the current recursive method for identifying the first continuous callback can cause the compiler to give up on type inference, especially when there are many callbacks. The fallback then allocates.
This switches this function to using a generated function (along with an inline function that takes splatted tuples). Because this generated function explicitly unrolls the tuple, there are no type inference problems.
I added a test that allocates using the old implementation (about 19kb allocations!) but does not with the new function. If I remove one of the callbacks, the allocations no longer happen with the recursive function, so it might be dependent on e.g. the specific Julia version to determine the point where the compiler gives up on …
=> Switch find_first_continuous_callback to use a generated implementation.

src/solve.jl, test/downstream/solve_error_handling.jl
```julia
using DifferentialEquations
f(du, u, p, t) = du .= 1.01u
function g(du, u, p, t)
du[1, 1] = 0.3u[1]
du[1, 2] = 0.6u[1]
du[1, 3] = 0.9u[1]
du[1, 4] = 0.12u[1]
du[2, 1] = 1.2u[2]
du[2, 2] = 0.2u[2]
du[2, 3] = 0.3u[2]
du[2, 4] = 1.8u[2]
end
prob = SDEProblem(f, g, randn(ComplexF64,2), (0.0, 1.0), noise_rate_prototype =complex(zeros(2, 4)),noise=RealWienerProcess(0.0,zeros(3)))
sol = solve(prob)
```
```
ERROR: Noise sizes are incompatible. The expected number of noise terms in the defined
`noise_rate_prototype` does not match the number of noise terms in the defined
`AbstractNoiseProcess`. Please ensure that
size(prob.noise_rate_prototype,2) == length(prob.noise.W[1]).
Note: Noise process definitions require that users specify `u0`, and this value is
directly used in the definition. …
```
=> Add a better error message for noise size incompatability

src/callbacks.jl, src/internal_falsi.jl, src/internal_itp.jl, src/solve.jl, test/callbacks.jl, test/downstream/solve_error_handling.jl, test/forwarddiff_dual_detection.jl, test/internal_rootfinder.jl
=> Fix unwanted type promotion in InternalITP

src/solve.jl
The correct `alg` is decided in 
https://github.com/SciML/DiffEqBase.jl/blob/2dd4fafdf4857902a4401f11ae7e22934113a9f3/src/solve.jl#L1426-L1431
we should use it.
Fixes https://github.com/SciML/SciMLSensitivity.jl/issues/907
=> use correct `alg`

.github/workflows/CI.yml, .github/workflows/Downstream.yml, Project.toml, src/DiffEqBase.jl, src/common_defaults.jl, src/termination_conditions.jl
Leads to quite a bit of type instability in the cache of the NonlinearSolve Algorithms. I will prototype a version there as well to see if this fixes things!
=> Rework the Termination Condition API to be type stable

ext/DiffEqBaseUnitfulExt.jl, src/utils.jl, test/utils.jl
from the type of `u` and `t`
This is designed to simplify handling in `OrdinaryDiffEq` which reimpliments this logic several times (and gets the `unitful` version wrong).
=> add `_rate_prototype` function for getting the type of `du`

Project.toml, src/solve.jl
See https://github.com/SciML/NonlinearSolve.jl/pull/292
=> Allow additional kwargs for NonlinearSolve

.github/workflows/Downstream.yml, Project.toml, src/common_defaults.jl
RMS-Norm causes problem with some of the algorithms, especially TR and Bad-Broyden Updates
We could use Inf Norm for size invariance but I haven't tested it out
=> Change the default norm for NonlinearSolve to norm(_, 2)

Project.toml, src/termination_conditions.jl
This leads to quite a few false positives. It is good to have as default in libraries like DEQs.jl but not the most appropriate in NonlinearSolve.jl
=> Disable protective check by default

src/solve.jl, test/downstream/solve_error_handling.jl
```julia
julia>  solve(prob,Tsit5())
ERROR: Non-Number element type inside of an `Array` detected.
Arrays with non-number element types, such as
`Array{Array{Float64}}`, are not supported by the
solvers.
If you are trying to use an array of arrays structure,
look at the tools in RecursiveArrayTools.jl. For example:
If this was a mistake, promote the element types to be
all the same. If this was intentional, for example,
using Unitful.jl with different unit values, then use
an array type which has fast broadcast support for
heterogeneous values such as the ArrayPartition
from RecursiveArrayTools.jl. For example:
```julia
using RecursiveArrayTools
u0 = ArrayPartition([1.0,2.0],[3.0,4.0])
u0 = VectorOfArray([1.0,2.0],[3.0,4.0])
```
are both initial conditions which would be compatible with …
```
=> Throw a nicer error if eltype is not a number

ext/DiffEqBaseReverseDiffExt.jl
Fixes https://github.com/SciML/SciMLSensitivity.jl/issues/943
```julia
using DifferentialEquations
using SciMLSensitivity.SciMLBase: RightRootFind
using SciMLSensitivity
using ForwardDiff, ReverseDiff, Zygote, FiniteDiff
using Test
GRAVITY = 9.81
MASS = 1.0
NUM_STATES = 2
t_start = 0.0
t_step = 0.05
t_stop = 2.0
tData = t_start:t_step:t_stop
u0 = [1.0, 0.0] # start state: ball position (1.0) and velocity (0.0)
p = [GRAVITY, MASS]
function fx(u, p, t)
g, m = p
return [u[2], -g]
end
ff = ODEFunction{false}(fx)
prob = ODEProblem{false}(ff, u0, (t_start, t_stop), p)
function loss(p)
solution = solve(prob; p=p, alg=solver, saveat=tData, sensealg=sensealg, abstol=1e-10, reltol=1e-10)
if !isa(solution, ReverseDiff.TrackedArray) && !isa(solution, Array)
sum(abs.(collect(u[1] for u in …
```
=> Fix TrackedArray reshaping

ext/DiffEqBaseEnzymeExt.jl
The rule was registered in Enzyme.reverse instead of EnzymeRules.reverse.
=> Fix EnzymeRules reverse register

src/callbacks.jl, test/downstream/community_callback_tests.jl
…
fixes https://github.com/SciML/OrdinaryDiffEq.jl/issues/2127
=> reinitialize DAEs in between calling `callback.affect!` and the second `savevalues!`

src/forwarddiff.jl, test/forwarddiff_dual_detection.jl
This addresses https://github.com/SciML/DiffEqBase.jl/issues/1009 by adding appropriate methods for `DiffResults.DiffResult` to `anyeltypedual()` which prevents upconversion of states to ForwardDiff.Dual numbers. Since DiffResults.DiffResult types are only used for pre-allocating outputs, this follows the spirit of the methods used for `ForwardDiff.AbstractConfig` and `PreallocationTools.FixedSizeDiffCache`.
=> Add anyeltypedual methods ignoring  DiffResults.DiffResult in Dual upconversion

src/forwarddiff.jl, test/forwarddiff_dual_detection.jl
While I was looking at this, I broadened a few `Set` and `Array` to `AbstractSet` and `AbstractArray` to better support non-base types.
=> fix `anyeltypedual(::Union)` and a few minor cleanups

src/solve.jl
Found this coming from `NonlinearSystems` where `structural_simplify` reduces the equations to 0, hence `u0` becomes nothing and `resid_prototype` becomes nothing.
MWE:
```julia
@variables u1
@parameters k=1.0 r=1.0 u2=1.0
eq = [0 ~ -u2 + (k - u1)/r]
@named n = NonlinearSystem(eq, [u1], [u2, k, r])
sys = structural_simplify(n)
np = NonlinearLeastSquaresProblem(sys, [], [u2 => 1.0, k => 1.0, r => 1.0])
sol = solve(np)
sol[u1]
```
=> fix: fallback to empty vector when resid_prototype is nothing for NonlinearLeastSquaresProblem

Project.toml, ext/DiffEqBaseTrackerExt.jl, src/solve.jl
If `p` is not extracted before, then it tries to promote `u0` to the tracked type.
=> Incorrect ordering of promotion

src/common_defaults.jl
I'm not 100% sure this is necessary, but it is at least a good bit more principled. There really isn't a reason to exclude `Inf` or `-1e150` as unstable u values.
=> check for large negative values and Infs in the unstable check

src/solve.jl
Some internal refactoring lead to an issue that kwargs might be accessed although they are not defined (i.e. has_kwargs = false).
=> Just use kwargs if they are defined for abstract problems.

ext/DiffEqBaseEnzymeExt.jl
Uses Enzyme's `make_zero` util instead of manually zeroing out the derivative variable. 
Needed for SciML/NonlinearSolve.jl#439 to make the Enzyme rule compatible with `NonlinearProblem`
=> use Enzyme make_zero

src/DiffEqBase.jl
`@recompile_invalidations` should only be used in very specific scenarios, and this is not one of those scenarios. Also, there are big changes being done with https://github.com/SciML/CommonWorldInvalidations.jl. With that, we only need to `@recompile_invalidations` on a few entry points. In particular, Static.jl, Symbolics.jl, and preferably ForwardDiff.jl and StaticArrays.jl would adopt it too. But this means that in order to handle all of this effectively, in SciML we only need to apply it on Static.jl, Symbolics.jl, and SciMLBase.jl and the whole ecosystem should be fine.
In any case, this library doesn't need it. It shouldn't make a tangible difference in compile times, while it increases precompile times by a lot.
=> Remove recompile_invalidations

src/DiffEqBase.jl, src/integrator_accessors.jl, src/solve.jl
This is needed for https://github.com/SciML/DiffEqCallbacks.jl/pull/229, but shouldn't get merged until we are settled that https://github.com/SciML/DiffEqCallbacks.jl/pull/229 has the correct approach (and doesn't need changes here).
=> add integrator accessors for dispatch purposes

src/forwarddiff.jl, test/forwarddiff_dual_detection.jl
=> make `promote_u0` use `isequal` rather than `==`

src/callbacks.jl
https://github.com/SciML/SciMLBase.jl/actions/runs/10806083008/job/29974255072?pr=784#step:6:1734
=> fix: access `callback.initializealg` instead of `.initialize_alg`

src/solve.jl
Documentation change: add doc for the `u0` and `p` keyword arguments in the `solve` call, e.g. as used in
https://docs.sciml.ai/SciMLSensitivity/stable/manual/differential_equation_sensitivities/#Using-and-Controlling-Sensitivity-Algorithms-within-AD
=> doc: u0, p keyword arg in solve()

src/fastpow.jl, src/solve.jl, src/termination_conditions.jl
Part of https://github.com/SciML/BoundaryValueDiffEq.jl/pull/216
Allow `u0` in BVProblem as AbstractArray for providing an initial guess
=> Allow u0 in BVProblem as Vector initial guess

src/callbacks.jl
possibly fixes https://github.com/SciML/DiffEqBase.jl/pull/1096
I don't think we need to support it since this is an internal feature and OrdinaryDiffEq now uses the better version of this.
=> remove `hasmethod` from callback

src/forwarddiff.jl, test/forwarddiff_dual_detection.jl
Fixes https://github.com/SciML/DiffEqBase.jl/issues/1074
=> Handle empty Kwargs case in forwarddiff detection

src/callbacks.jl
Depends on https://github.com/SciML/SciMLBase.jl/pull/842
=> Set change_t_via_interpolation! to use the init mode from the callback

src/solve.jl
- [ x] Any code changes were done in a way that does not break public API
- [ x] All documentation related to code changes were updated
- [ x] The new code follows the
- [ x] Any new documentation only uses public API
This adds `alias` to the list of acceptable common solve kwargs. 
Also bumps the minor version since technically it's a new "feature" I think?
=> Add `alias` to acceptable kwargs for Aliasing API

ext/DiffEqBaseGTPSAExt.jl, test/downstream/gtpsa.jl
I added an overload for `ODE_DEFAULT_NORM` with `TPS` types where it calculates the 2-norm of the scalar (0th order) part of the `TPS`, and is necessary because the GTPSA C library does not allow `sqrt(TPS(0))` as the derivatives are undefined. 
The calculation of the norm of the scalar part follows from what I see in the `Tracker` extension. If instead it should calculate a norm including all monomial coefficients/partial derivatives, I can quickly change that to the function `GTPSA.normTPS`.
=> Add `ODE_DEFAULT_NORM` overload for GTPSA

Project.toml, ext/DiffEqBaseForwardDiffExt.jl, ext/DiffEqBaseReverseDiffExt.jl, src/utils.jl, test/forwarddiff_dual_detection.jl
I think this is necessary and should fix downstream issues I just ran into:
```julia
Got exception outside of a @test
MethodError: no method matching totallength(::Vector{ForwardDiff.Dual{ForwardDiff.Tag{Pumas.Tag, ForwardDiff.Dual{ForwardDiff.Tag{Pumas.Tag, Float64}, Float64, 2}}, ForwardDiff.Dual{ForwardDiff.Tag{Pumas.Tag, Float64}, Float64, 2}, 1}})
The function `totallength` exists, but no method is defined for this combination of argument types.
Closest candidates are:
totallength(::ForwardDiff.Dual)
@ DiffEqBaseForwardDiffExt ~/.julia/packages/DiffEqBase/DnAEG/ext/DiffEqBaseForwardDiffExt.jl:504
```
=> Import `totallength` in ForwardDiff extension

src/solve.jl
=> Aliasing API Docstring

test/downstream/Project.toml, test/downstream/default_linsolve_structure.jl, test/downstream/labelledarrays.jl, test/gpu/Project.toml, test/gpu/simple_gpu.jl
I noticed test failures in https://github.com/SciML/OrdinaryDiffEq.jl/pull/2617 due to incorrectly specified `diff_type` in the GPU tests - `Val{:central}` should be `Val(:central)` etc. This also showed up in recent buildkite runs on the DiffEqBase master branch: https://buildkite.com/julialang/diffeqbase-dot-jl/builds/1952#019513f2-5ba8-4380-bcb7-b047e9198da3/324-1050
Instead of fixing the `diff_type`s, I assumed it would be more future-proof to switch the tests to ADTypes (and hence only specify `autodiff`).
=> Use ADTypes in tests

src/solve.jl
=> fix: pass `retcode` as kwarg

src/callbacks.jl
This is because the norm on (u=tracked, t=tracked) returns a tracked value, which is required for differentiating appropriately w.r.t. callback time. However, this value is just being saved for non-differentiable logic in order to know whether to include the first interval or not in the search process, and so it should be dropped.
=> Fix downstream AD tests

src/internal_itp.jl
Background is here: https://github.com/SciML/DiffEqBase.jl/pull/1127/files#r2022436123
To summarize: inside the branch where the callback condition is evaluated to an exact zero, this PR fills the `left` and `right` fields of the solution with the location of the zero crossing instead of the values at the start of that ITP iteration.
=> Tighten the interval returned by InternalITP when there's an exact zero crossing

.github/workflows/Downstream.yml
https://github.com/SciML/SciMLSensitivity.jl/pull/1189 highlights that the downstream tests that are failing for SciMLSensitivity.jl are actually Enzyme issues with v1.11. These are now being tracked here https://github.com/EnzymeAD/Enzyme.jl/issues/2318 for the Enzyme developers to work on. But there are certain things we've been weary about, like:
* https://github.com/SciML/SciMLBase.jl/pull/997
* https://github.com/SciML/SciMLBase.jl/pull/998
Because of failing downstream tests. But that's counter productive: we're not improving our autodiff interfaces because we see failures, but those aren't failures of our autodiff interfaces, those are Enzyme failures.
So for now the solution seems to be to go to v1.10 in these downstream tests and increase the coverage of SciMLSensitivity, and …
=> Improve Downstream testing

ext/DiffEqBaseMonteCarloMeasurementsExt.jl
=> fix: fix method ambiguity in `promote_u0` in MonteCarloExt

Project.toml, src/solve.jl, test/downstream/null_de.jl
We actually know the entire time series for the solution, so we should state that we know that via `dense=true`.
```julia
using OrdinaryDiffEqDefault, ModelingToolkit
using ModelingToolkit: t_nounits as t, D_nounits as D
@variables x(t) y(t)
eqs = [y ~ x, y ~ sin(t)]
@mtkbuild sys = ODESystem(eqs, t)
tspan = (0.0, 10.0)
prob = ODEProblem(sys, [], tspan)
sol = solve(prob)
using Plots
plot(sol, idxs = [x])
savefig("plot.png")
```
Before and after
=> Mark null ODE solutions as dense

ext/DiffEqBaseEnzymeExt.jl, test/runtests.jl
This triggers failures here and downstream because if Enzyme is in the environment this tries to precompile. Thus because we know Enzyme won't work on prereleases, we are disabling the extension
=> Disable Enzyme extension on prerelease

ext/DiffEqBaseGTPSAExt.jl, ext/DiffEqBaseGeneralizedGeneratedExt.jl, ext/DiffEqBaseMPIExt.jl, ext/DiffEqBaseMeasurementsExt.jl, ext/DiffEqBaseMonteCarloMeasurementsExt.jl, ext/DiffEqBaseTrackerExt.jl, ext/DiffEqBaseUnitfulExt.jl
This PR removes the compatibility checks for `isdefined(Base, :get_extension)` since all SciML packages now require Julia v1.10+, where package extensions are built-in.
- Removed unnecessary version checks in extension loading code
- Simplified extension imports by removing conditional logic
- Cleaned up obsolete compatibility code
As identified in the SciML-wide analysis, all SciML packages have moved to requiring Julia v1.10+ as the minimum version. This makes the compatibility code for checking whether package extensions are available redundant.
The `isdefined(Base, :get_extension)` checks were used to support Julia v1.9 where extensions were loaded differently. Since we no longer support v1.9, this code can be safely removed.
=> Remove Julia v1.9 get_extension compatibility code

src/solve.jl, test/downstream/null_de.jl
=> fix: fix `step!` without `dt` for `NullODEIntegrator`

test/diffeqfunction_tests.jl
https://github.com/SciML/SciMLBase.jl/pull/1101 made it so that `(SciMLBase.AbstractSciMLFunction <: Function) == false` which broke tests here. This makes those tests working again.
=> fixes tests that were broken by SciMLBase PR 1101

Project.toml, src/dae_initialization.jl
- Remove the `BrownBasicInit` alias and keep only `BrownFullBasicInit` as the primary struct name
- Simplifies the API by having a single name for this initialization algorithm
- Bump version to 6.190.2
- Changed `struct BrownBasicInit` to `struct BrownFullBasicInit` 
- Removed the `const BrownFullBasicInit = BrownBasicInit` alias line
- Updated exports to only export `BrownFullBasicInit`
- Updated docstring to reflect the new name
This is a breaking change for code that uses `BrownBasicInit` directly, but maintains compatibility for code using `BrownFullBasicInit`.
Related to ongoing work in OrdinaryDiffEq and Sundials packages to use the extended initialization algorithms from DiffEqBase.
=> Remove BrownBasicInit alias, keep only BrownFullBasicInit
