- src/DiffEqBase.jl
Tests not passing, but that should be a unrelated malaise?  If that is the case, then please merge this.
> Exporting solve

- src/DiffEqBase.jl
- src/problems/imex_problem.jl
- src/problems/splitode_problem.jl
> Imex problem

- src/problems/constrained_ode_problems.jl
- src/problems/dae_problems.jl
- src/problems/dde_problems.jl
- src/problems/discrete_problems.jl
- src/problems/ode_problems.jl
- src/problems/rode_problems.jl
- src/problems/sde_problems.jl
> Use 'promote_type(map(typeof,tspan)...)' instead of 'eltype(tspan)'

- src/DiffEqBase.jl
- src/integrator_interface.jl
- src/solutions/solution_interface.jl
Per Tim Holy's comments, following the code in Unitful.jl
> Don't use Ranges in v0.6

- src/DiffEqBase.jl
Forgot to remove those before.
> Remove unneeded exports

- test/problem_creation_tests.jl
This is just to demonstrate that the tests fail at the moment.
> Test problem constructors against @inferred

- test/remake_tests.jl
Forgot to test the other path in `remake`.
> Add more tests for remake

- src/problems/problem_traits.jl
- test/remake_tests.jl
We need `isinplace` for it work.
> Make remake work with SplitFunction

- src/callbacks.jl
https://github.com/JuliaDiffEq/DiffEqDocs.jl/issues/81#issuecomment-367146902
I should say I didn't test anything :)
> Use u_modified! in INITIALIZE_DEFAULT

- src/integrator_interface.jl
as discussed in:
https://github.com/JuliaDiffEq/StochasticDiffEq.jl/pull/56#discussion_r177317635
> Add default implementation of set_ut!

- src/solutions/solution_interface.jl
> Add detection in recipe for log xscale and space t appropriately

- src/utils.jl
- test/runtests.jl
- test/tabletraits_tests.jl
https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/271
Incidentally, I was playing with DiffEqBase to make it work with nightly :)
It turned out just a few tweaks to the code makes the unit test happy.
> Initiate Julia 1.0 support

- src/integrator_interface.jl
- test/integrator_tests.jl
closes https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/280
> Return nothing from step!(integrator, dt)

- src/integrator_interface.jl
- src/solutions/solution_interface.jl
Backport @YingboMa's #134 to 0.7 branch.
> Fix plot recipe for `sol` (backport to 0.7)

- src/DiffEqBase.jl
- src/problems/noise_problems.jl
- src/problems/ode_problems.jl
- src/remake.jl
- src/utils.jl
- test/remake_tests.jl
> Fixing remake

- src/DiffEqBase.jl
- src/problems/noise_problems.jl
- src/problems/ode_problems.jl
- src/remake.jl
- src/utils.jl
- test/remake_tests.jl
@tkf what about removing the branch by just adding a method to `NoiseProblem`?
> remove remake branch

- src/problems/dae_problems.jl
- src/problems/dde_problems.jl
- src/problems/discrete_problems.jl
- src/problems/rode_problems.jl
- src/problems/sde_problems.jl
- src/problems/steady_state_problems.jl
- src/remake.jl
- test/remake_tests.jl
> Implement T{iip}(; kwargs...) constructors for remake

- appveyor.yml
Copied from https://github.com/JuliaCI/Appveyor.jl and then tweaked `environment.matrix`.
> Use Appveyor.jl

- src/interpolation.jl
- src/solutions/dae_solutions.jl
- src/solutions/ode_solutions.jl
- src/solutions/rode_solutions.jl
Ref: https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/203
> Change interpolation API for #203

- src/interpolation.jl
We really should have some tests for the interpolations, though I don't know how...
> Fix variable names in interpolation

- src/integrator_interface.jl
~If `tdt` is true, then step to `dt`.~
```julia
step!(integ::DEIntegrator, dt::Real, stop_at_tdt = false, tdt = false)
```
> tdir handling in `step!`

- src/diffeqfunction.jl
According to the benchmarks, the counter inside the function caused extra allocation and time. Before DEStats, the following code:
```
using OrdinaryDiffEq, BenchmarkTools
function f(du,u,p,t)
du[1] = -p[1]*u[1] + p[3]*u[2]*u[3]
du[2] = p[1]*u[1] - p[2]*u[2]^2 - p[3]*u[2]*u[3]
du[3] = p[2]*u[2]^2
end
u0=[0.5,0.5,0.5]
tspan = (0.0,1.0)
p = (k₁=4, k₂=5, k₃=6,)
prob = ODEProblem(f,u0,tspan,p)
@btime sol = solve(prob,Rosenbrock23(),reltol=1e-8,abstol=1e-8)
```
gave results : `396.663 μs (2366 allocations: 168.94 KiB)`
After DEstats: `552.578 μs (6118 allocations: 255.81 KiB)`
This PR fixes this extra resoures problem and benchmarks now are: `397.641 μs (2367 allocations: 169.03 KiB)`
> Reverts nfeval calculation inside DEFunction

- src/callbacks.jl
- test/destats_tests.jl
I guess this completes the new changes in DEStats in #196 .
> Counts number of  root finds

- src/diffeqfastbc.jl
- test/fastbc.jl
Fix https://github.com/JuliaDiffEq/DiffEqBase.jl/issues/203
> Compatibility with Julia 1.0

- src/callbacks.jl
We may want to try/catch using a dual number as well?
> Safer epsilon in callback and handle callback switch off

- src/callbacks.jl
Ref: https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/754#discussion_r290498095
> Fixes type broken inference

- src/callbacks.jl
I am running complete ODE tests right now, once they pass, then it should be merged.
> Fix callback tests failures

- src/callbacks.jl
This was increased in #221 but caused OrdinaryDiffEq tests to fail.
> Fix OrdinaryDiffEq failures

- src/solve.jl
- test/high_level_solve.jl
Allow to specify constant lags as function of the form `(p) -> [lags...]`.
> Allow functional constant lags

- src/solutions/ode_solutions.jl
Part of https://github.com/JuliaDiffEq/DelayDiffEq.jl/issues/114.
> Change interface of analytical solutions of DDEs

- src/nlsolve/utils.jl
Implements function `nlsolve_resize!` for resizing all the nlsolver stuff. All that remains is resizing W and J, which was an issue previously too.
> Resizing nlsolver things

- src/DiffEqBase.jl
- src/linear_nonlinear.jl
@YingboMa I think we can't do the stationary methods because they can't do the preconditioners?
> Expand iterative solver support

- src/nlsolve/newton.jl
Ref: https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/798
> W transform in Newton iteration

- src/solutions/dae_solutions.jl
I tried to update the computation of errors for DAE solutions by taking inspiration from the handling of ODE solutions. By the way, it seems that in https://github.com/JuliaDiffEq/Sundials.jl/blob/master/src/common_interface/solve.jl#L970-L978 `dures` is not passed, so field `du` of the `DAESolution` was (and is) always `nothing` and is only implicitly present as part of the interpolation.
> Update calculation of errors of DAE solution

- Project.toml
- src/DiffEqBase.jl
- src/diffeqfunction.jl
- src/init.jl
- src/linear_nonlinear.jl
- test/downstream/default_linsolve_structure.jl
- test/gpu/simple_gpu.jl
- test/runtests.jl
```julia
using LinearAlgebra, DifferentialEquations
f = (du,u,p,t) -> du .= u ./ t
jac = (J,u,p,t) -> (J[1,1] = 1/t; J[2,2] = 1/t; J)
jp = Diagonal(zeros(2))
fun = ODEFunction(f; jac=jac, jac_prototype=jp)
prob = ODEProblem(fun,ones(2),(1.0,10.0))
solve(prob,Rosenbrock23(autodiff=false))
```
> structured matrix fast paths

- Project.toml
- src/nlsolve/functional.jl
Fixes https://github.com/JuliaDiffEq/DiffEqBase.jl/issues/310.
> Fix update of norm of residuals

- src/problems/analytical_problems.jl
- src/problems/bvp_problems.jl
- src/problems/dae_problems.jl
- src/problems/dde_problems.jl
- src/problems/discrete_problems.jl
- src/problems/ode_problems.jl
- src/problems/problem_utils.jl
- src/problems/rode_problems.jl
- src/problems/sde_problems.jl
- src/problems/steady_state_problems.jl
- test/downstream/null_params_test.jl
- test/runtests.jl
Let's tell the people why they got a MethodError!
> Add NullParameters default for better error messages

- src/DiffEqBase.jl
- src/diffeqfunction.jl
- src/problems/problem_traits.jl
- src/problems/sdde_problems.jl
- src/solutions/rode_solutions.jl
Added files, types and functions necessary to include StochasticDelayDiffEq.jl in the near future
> Base functionality of StochasticDelayDiffEq

- src/DiffEqBase.jl
- src/problems/basic_problems.jl
- src/problems/problem_traits.jl
- src/problems/problem_utils.jl
- src/solutions/basic_solutions.jl
- test/problem_creation_tests.jl
One step forward in https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/469
> Add Linear, Nonlinear, and Quadrature Problems

- Project.toml
- src/operators/basic_operators.jl
Edits the basic operators to allow them to work with higher dimensional domains.
> Basic operators on multi dimensional domains

- src/callbacks.jl
Reviews @ChrisRackauckas, if you want to dig into Callback Code again :stuck_out_tongue:
> Fix VectorContinousCallback

- src/common_defaults.jl
- src/init.jl
Fixes https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/518
> faster default norms

- src/callbacks.jl
- src/init.jl
Requires https://github.com/JuliaGPU/CuArrays.jl/pull/446
> Use optimized findall on GPU

- Project.toml
- src/DiffEqBase.jl
- src/integrator_interface.jl
ignore small tstops when checking if dt is large enough, since this is a user-imposed small dt
> tstop lumping

- src/init.jl
https://github.com/JuliaLang/julia/issues/31278
@antoine-levitt
> Add required ldiv! overloads

- src/integrator_interface.jl
Fixes https://github.com/JuliaDiffEq/DelayDiffEq.jl/pull/164 which is a really weird edge case.
> catch edge case of large dtmin to end

- src/fastpow.jl
A simple fix for the zero case.
> Fix fastpow zero limit

- src/data_array.jl
- test/data_array_tests.jl
- test/downstream/data_array_regression_tests.jl
- test/runtests.jl
Fixes https://github.com/JuliaDiffEq/StochasticDiffEq.jl/issues/247, https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/525, https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/336. I'll go find more.
> add a broadcast overload for DEDataArray

- Project.toml
- src/DiffEqBase.jl
- src/zygote.jl
Not the end of the story, but a good start.
> add some basic ZygoteRules

- src/callbacks.jl
- src/integrator_interface.jl
Adds docstrings for various APIs of DiffEqBase. Shifting the documentation from just markdown to docstrings. Managing documentation should be easier then.
> WIP: Adds Docstrings

- src/init.jl
@KristofferC 1.4 is the correct bound?
> remove piracy overload on 1.4

- src/init.jl
Better bound than https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/412 . Thanks @KristofferC and @thofma !
> Better bound

- src/solutions/dae_solutions.jl
> Bugfixes in calculate_solution_errors

- src/init.jl
```julia
using OrdinaryDiffEq
const N = 32
const xyd_brusselator = range(0,stop=1,length=N)
brusselator_f(x, y, t) = (((x-0.3)^2 + (y-0.6)^2) <= 0.1^2) * (t >= 1.1) * 5.
limit(a, N) = a == N+1 ? 1 : a == 0 ? N : a
function brusselator_2d_loop(du, u, p, t)
A, B, alpha, dx = p
alpha = alpha/dx^2
@inbounds for I in CartesianIndices((N, N))
i, j = Tuple(I)
x, y = xyd_brusselator[I[1]], xyd_brusselator[I[2]]
ip1, im1, jp1, jm1 = limit(i+1, N), limit(i-1, N), limit(j+1, N), limit(j-1, N)
du[i,j,1] = alpha*(u[im1,j,1] + u[ip1,j,1] + u[i,jp1,1] + u[i,jm1,1] - 4u[i,j,1]) +
B + u[i,j,1]^2*u[i,j,2] - (A + 1)*u[i,j,1] + brusselator_f(x, y, t)
du[i,j,2] = alpha*(u[im1,j,2] + u[ip1,j,2] + u[i,jp1,2] + u[i,jm1,2] - 4u[i,j,2]) +
A*u[i,j,1] - u[i,j,1]^2*u[i,j,2]
end
end
p = (3.4, 1., 10., …
```
> Add MKLPardiso linear solver

- Project.toml
- src/zygote.jl
Allows differentiating through code that defines an ODEProblem. Fixes https://github.com/JuliaDiffEq/DiffEqSensitivity.jl/issues/193
> Add missing adjoint for numargs

- src/init.jl
> Make Pardiso compatible with complex

- src/utils.jl
> Fix units in dtmin

- src/diffeqfunction.jl
Needed to make the last iteration of https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/1054 work.
> Allso setting both jac_prototype and sparsity

- Project.toml
- src/operators/basic_operators.jl
- src/operators/common_defaults.jl
- test/basic_operators_interface.jl
Fix https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/1080
> Fix DiffEqArrayOperator broadcast

- Project.toml
- src/solve.jl
- test/callbacks.jl
Fixes https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/578
> Fix and test automatic callback merging

- src/callbacks.jl
- src/init.jl
Reverts SciML/DiffEqBase.jl#476
> Revert "Fix bisection to make it not return tprev"

- src/diffeqfastbc.jl
Fixes https://github.com/SciML/DifferentialEquations.jl/issues/593
Xref: https://github.com/JuliaLang/julia/pull/35260
> Only manually inline broadcast until fix

- src/integrator_interface.jl
> Better set_proposed_dt! error

- src/callbacks.jl
- src/integrator_interface.jl
@ChrisRackauckas this is non-breaking, making a PR to Sundials
> Adds is_integrator_adaptive to integrator interface

- src/ensemble/basic_ensemble_solve.jl
- src/ensemble/ensemble_problems.jl
- test/downstream/distributed_ensemble.jl
- test/downstream/ensemble.jl
- test/runtests.jl
Fixes https://github.com/SciML/DiffEqBase.jl/issues/495 and fixes https://github.com/SciML/DiffEqBase.jl/issues/494
> Fix splitthreads trajectory choices and test it better

- src/data_array.jl
- test/data_array_tests.jl
- test/runtests.jl
This PR closes the issue #507. Notice that, due to the discussion in #507, I had to move the test file `data_array_tests.jl` to the beginning of the set to test the new code.
> Support for immutable fields derived from AbstractArray

- src/ensemble/basic_ensemble_solve.jl
```julia
using DiffEqBase
using DiffEqJump
sr = [1.0,2.0,50.]
maj = MassActionJump(sr,[[1 => 1],[1 => 1],[0 => 1]], [[1 => 1], [1 => -1], [1 => 1]])
params = (1.0,2.0,50.)
tspan = (0.,4.)
u0 = [5]
dprob = DiscreteProblem(u0, tspan, params)
jprob = JumpProblem(dprob, Direct(), maj)
solve(EnsembleProblem(jprob), SSAStepper(), EnsembleThreads(); trajectories=10)
solve(EnsembleProblem(jprob;safetycopy=true), SSAStepper(), EnsembleThreads(); trajectories=10)
@time for i in 1:10000 solve(EnsembleProblem(jprob), SSAStepper(), EnsembleThreads(); trajectories=1) end
1.862159 seconds (7.06 M allocations: 2.128 GiB, 13.37% gc time)
1.723136 seconds (7.07 M allocations: 2.128 GiB, 12.32% gc time)
1.770109 seconds (7.08 M allocations: 2.130 GiB, 11.39% gc time)
1.632181 seconds (7.07 M allocations: …
```
> avoid a bunch of multithreading overheads

- Project.toml
- src/init.jl
- src/reversediff.jl
- src/solve.jl
- src/tracker.jl
MWE:
```julia
using DiffEqSensitivity, OrdinaryDiffEq, Zygote
using RecursiveArrayTools: DiffEqArray
using Test, ForwardDiff
using Tracker, ReverseDiff
function fiip(du,u,p,t)
du[1] = dx = p[1]*u[1] - p[2]*u[1]*u[2]
du[2] = dy = -p[3]*u[2] + p[4]*u[1]*u[2]
end
function foop(u,p,t)
dx = p[1]*u[1] - p[2]*u[1]*u[2]
dy = -p[3]*u[2] + p[4]*u[1]*u[2]
[dx,dy]
end
function foop(u::Tracker.TrackedArray,p,t)
dx = p[1]*u[1] - p[2]*u[1]*u[2]
dy = -p[3]*u[2] + p[4]*u[1]*u[2]
Tracker.collect([dx,dy])
end
p = [1.5,1.0,3.0,1.0]; u0 = [1.0;1.0]
prob = ODEProblem(fiip,u0,(0.0,10.0),p)
proboop = ODEProblem(foop,u0,(0.0,10.0),p)
sol = concrete_solve(prob,Tsit5(),abstol=1e-14,reltol=1e-14)
_sol = solve(prob,Tsit5(),abstol=1e-14,reltol=1e-14)
ū0,adj = adjoint_sensitivities(_sol,Tsit5(),((out,u,p,t,i) -> out …
```
> Tracker and ReverseDiff custom concrete_solve gradients

- src/ensemble/basic_ensemble_solve.jl
- test/downstream/ensemble_thread_safety.jl
- test/runtests.jl
Fixes https://github.com/SciML/DiffEqDocs.jl/issues/361
> fix multithreaded thread safety and clean up

- src/solve.jl
cf. https://discourse.julialang.org/t/how-to-switch-ode-from-differentialequations-to-ordinarydiffeq/40460/2
> More explanatory error message when missing algorithm

- Project.toml
- src/solve.jl
Fixes https://github.com/SciML/DifferentialEquations.jl/issues/620
> Check pointer not values when deciding whether to remake

- src/solve.jl
- test/high_level_solve.jl
We even have a warning on this already for some cases, but if we know exactly when it's going to fail and why... let's just be nice.
Fixes https://github.com/SciML/DifferentialEquations.jl/issues/631 and infinitely many other times this has came up. Might as well just be nice.
> auto-convert integer inputs

- .gitignore
- src/DiffEqBase.jl
- src/diffeqfunction.jl
- src/problems/ode_problems.jl
This is the bare minimum we need for incrementing forms, we can discuss what all things might make sense.
> IncrementingODEProblem and IncrementingODEFunction

- src/remake.jl
Probably enough 🤣 @ChrisRackauckas
> Remake for DEAlgorithm

- Project.toml
- src/integrator_interface.jl
This PR allows unitful step size.
> Remove unnecessary type constraint

- src/DiffEqBase.jl
Fixes https://github.com/SciML/DiffEqSensitivity.jl/issues/306
> export SensitivityADPassThrough

- src/callbacks.jl
> Add branch for tprev in get_condition

- src/solve.jl
- test/downstream/ad_tests.jl
Fixes https://discourse.julialang.org/t/derivative-with-terminate-callback/46409
> use u0_promote to ensure tspan promotes with callbacks

- src/ensemble/basic_ensemble_solve.jl
If you'd prefer to keep `batch_function`, I could try a `let` block instead.
On Julia 1.5.1, before this PR:
```julia
#__solve#356::Core.Compiler.Const(DiffEqBase.#__solve#356, false)
trajectories::Int64
batch_size::Int64
pmap_batch_size::Int64
kwargs::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol,Symbol},NamedTuple{(:save_idxs, :saveat, :saveeverystep),Tuple{Array{Int64,1},StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},Bool}}}
@_6::Core.Compiler.Const(DiffEqBase.__solve, false)
prob::EnsembleProblem{ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,Array{Float64,1},ODEFunction{true,typeof(qsp!),UniformScaling{Bool},Nothing,Nothing,var"#1#2",Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Symbol,Disc …
```
> Fix type instability in EnsembleThreads.

- src/DiffEqBase.jl
- src/problems/basic_problems.jl
- src/problems/problem_utils.jl
> fix and update OptimizationProblem

- src/DiffEqBase.jl
- src/callbacks.jl
> add finalize option to callbacks

- Project.toml
- src/utils.jl
- test/problem_creation_tests.jl
PR:
```julia
julia> @ballocated NonlinearProblem((u,p)->u, 1.0)
0
```
Master:
```julia
julia> @ballocated NonlinearProblem((u,p)->u, 1.0)
5040
```
> Non-allocating isinplace

- .github/workflows/Test.yml
- Project.toml
- src/utils.jl
- test/problem_creation_tests.jl
Reverts SciML/DiffEqBase.jl#601
> Revert "Non-allocating isinplace"

- Project.toml
- src/solutions/solution_interface.jl
Ref: https://github.com/SciML/ModelingToolkit.jl/pull/679
Fix https://github.com/SciML/ModelingToolkit.jl/issues/636
> Prettify MTK generated names

- Project.toml
- src/solutions/solution_interface.jl
Fix https://github.com/SciML/ModelingToolkit.jl/issues/636
> Fix plot legends when syms already have dependent variables

- src/init.jl
Fixes https://github.com/SciML/DiffEqBase.jl/issues/615
> Remove upstreamed ForwardDiff overload

- src/common_defaults.jl
- test/ode_default_norm.jl
Fixed the bugs described in issue #619. Added the corresponding tests.
> Fixes #619

- src/linear_nonlinear.jl
@yingboma should it be abstol or reltol?
> update IterativeSolver bindings for breaking tol change

- src/callbacks.jl
similar to https://github.com/SciML/DelayDiffEq.jl/pull/200
> type inference in rootfinding

- src/solve.jl
Adds an `init` wrapper function for a discretized `PDEProblem` identical to what already exists for `solve`.
> Add init wrapper for discretized PDEProblem

- src/DiffEqBase.jl
- src/diffeqfunction.jl
- src/function_wrappers.jl
- src/problems/basic_problems.jl
Hi,
I have added parameters for jacobian calculation and helper functions for NonlinearProblem similar to ODEFunction and as pointed out in #635.
@ChrisRackauckas, please review.
> Add jacobian structures for NonlinearProblem

- src/DiffEqBase.jl
Fixes https://github.com/SciML/DifferentialEquations.jl/issues/727
> End the deprecation of MonteCarloProblem

- Project.toml
- src/init.jl
- test/downstream/ensemble_ad.jl
Finalizes the fix to https://github.com/SciML/DiffEqBase.jl/issues/658
> Fix the tmap adjoint

- Project.toml
- src/linear_nonlinear.jl
> Update openblas check for v1.7

- src/calculate_residuals.jl
- src/common_defaults.jl
Companion PR to https://github.com/SciML/OrdinaryDiffEq.jl/pull/1465
> reduce compile times by specializing broadcasts to loops

- src/DiffEqBase.jl
> Re-export types and aliases of DEDataArrays

- src/common_defaults.jl
this should fix the progress log when the value is a complex number
> fix complex value progress

- src/callbacks.jl
Fixes https://github.com/SciML/DifferentialEquations.jl/issues/792
> Fix event interpolation edge case

- src/solve.jl
Fixes the Tsit5 case from https://github.com/SciML/ModelingToolkit.jl/issues/1365
> Fix tspan promotion

- src/callbacks.jl
- test/downstream/community_callback_tests.jl
Fixes https://github.com/SciML/OrdinaryDiffEq.jl/issues/1528 and fixes https://github.com/SciML/DifferentialEquations.jl/issues/798
> Fix callback interp_points count in range construction

- Project.toml
- src/calculate_residuals.jl
- src/nlsolve/functional.jl
- src/nlsolve/newton.jl
- src/nlsolve/utils.jl
Should hopefully improve latency by reducing the amount of compiled code. In theory, should also improve runtime performance by a negligible amount due to removing a branch and reducing code size.
> Fast no broadcast

- Project.toml
- src/solve.jl
Reverts SciML/DiffEqBase.jl#770
> Revert "save_first should be an allowed kwarg"

- Project.toml
- src/solve.jl
Requires https://github.com/JuliaRegistries/General/pull/62583 in order to be safe.
> Add originators to the forward and adjoint calls

- src/common_defaults.jl
- test/ode_default_unstable_check.jl
- test/runtests.jl
`nonzeros` is not imported so the method currently throws an error.
> Fix UndefVarError for nonzeros

- Project.toml
- src/forwarddiff.jl
- test/forwarddiff_dual_detection.jl
Fixes https://github.com/SciML/DiffEqBase.jl/issues/774
> Document anyeltypedual, handle empty tuple case and higher order AD

- src/forwarddiff.jl
- test/forwarddiff_dual_detection.jl
Fixes https://github.com/SciML/DiffEqBase.jl/issues/776 and fixes https://github.com/SciML/DiffEqBase.jl/issues/779
> Even more ForwardDiff dual detection robustness

- src/forwarddiff.jl
- test/forwarddiff_dual_detection.jl
Fixes issues with using PreallocationTools and such inside of the parameters
> Opt configs out of the forwarddiff promotion

- src/forwarddiff.jl
- test/forwarddiff_dual_detection.jl
Fixes https://github.com/SciML/DiffEqBase.jl/issues/784
> Fix ForwardDiff Dual detection for circular references

- src/solve.jl
- test/downstream/solve_error_handling.jl
Fixes https://github.com/SciML/SciMLSensitivity.jl/issues/685
> Handle nothing + alg = alg

- src/DiffEqBase.jl
- src/solve.jl
Fixes https://github.com/SciML/OrdinaryDiffEq.jl/issues/1710
> allow step rejections instead of errors when hitting a singular matrix

- src/solve.jl
I think this should fix the issue I mentioned with kwargs not getting passed to solve from JumpProblem.
> fix JumpProblem kwarg passing

- src/forwarddiff.jl
- src/init.jl
- test/high_level_solve.jl
This follows the suggestion of @devmotion in https://github.com/SciML/OrdinaryDiffEq.jl/issues/1776#issuecomment-1268395677
Closes https://github.com/SciML/OrdinaryDiffEq.jl/issues/1776
> promote `tspan` with `dt`

- src/chainrules.jl
Fixes test failures in https://github.com/SciML/DiffEqGPU.jl/pull/189
Stacktrace:
https://buildkite.com/julialang/diffeqgpu-dot-jl/builds/292#0184a0f2-53f3-4695-a7a5-efd22555b388/531-961
> Update rrule for ODESolution

- src/solve.jl
- test/downstream/unwrapping.jl
Fixes https://github.com/SciML/DifferentialEquations.jl/issues/916
> Handle functional initial conditions with unwrapping

- src/solve.jl
- test/downstream/solve_error_handling.jl
Fixes https://github.com/SciML/SciMLBase.jl/issues/315
> Throw informative errors for incorrectly sized mass matrices

- .github/workflows/Downstream.yml
- src/solve.jl
Required for https://github.com/SciML/DifferentialEquations.jl/pull/935
> Automatically convert a SteadyStateProblem to a NonlinearProblem

- Project.toml
- src/DiffEqBase.jl
- src/callbacks.jl
- src/solve.jl
Requires https://github.com/SciML/SciMLBase.jl/pull/400
> add verbose print error messages to specialized excpetions

- src/DiffEqBase.jl
Fixes https://github.com/SciML/DiffEqBase.jl/issues/880
> Improve the SciMLOperator deprecation path

- test/downstream/null_params_test.jl
> Fix exception type

- Project.toml
- test/aqua.jl
This PR adds some aqua tests to CI.
> Add some aqua tests

- src/forwarddiff.jl
- test/aqua.jl
This PR fixes the method with unbound type arguments.
> Fix unbound args method

- src/solve.jl
- test/downstream/solve_error_handling.jl
Fixes https://github.com/SciML/OrdinaryDiffEq.jl/issues/1939
> Error if NaN is in tspan

- src/solve.jl
- test/downstream/kwarg_warn.jl
We have had this around for long enough to enable it.
> Change default kwargs handle from warn to error

- Project.toml
- ext/DiffEqBaseEnzymeExt.jl
- src/init.jl
Requires https://github.com/SciML/SciMLBase.jl/pull/496 and https://github.com/EnzymeAD/Enzyme.jl/pull/1056
> Add Enzyme extension

- ext/DiffEqBaseReverseDiffExt.jl
Fixes https://github.com/SciML/DiffEqBase.jl/issues/946
> Fix ReverseDiff capture overload ambiguities

- Project.toml
- src/solve.jl
Needs to wait on https://github.com/SciML/SciMLBase.jl/pull/500
> Add  NonlinearLeastSquaresProblem dispatches

- src/solve.jl
Required for https://github.com/SciML/NonlinearSolve.jl/pull/208
> Add termination_condition to solve options

- Project.toml
- src/common_defaults.jl
- src/termination_conditions.jl
* We need this to handle Complex Numbers
> Use `ODE_DEFAULT_NORM` for NonlinearSolve

- Project.toml
- src/solve.jl
See https://github.com/SciML/BoundaryValueDiffEq.jl/pull/133
> Propagate u0 function for BVPs

- src/fastpow.jl
Future proofs for https://github.com/JuliaLang/JuliaSyntax.jl/issues/378
> Future-safe the fastpow

- Project.toml
- src/solve.jl
- test/high_level_solve.jl
[contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [ScioML Style Guide](https://github.com/SciML/SciMLStyle) and
Fixes https://github.com/SciML/DifferentialEquations.jl/issues/995
> Remake with `p`

- src/common_defaults.jl
Let's wait for the CI to run on downstream for this, just to be sure.
> Fix Vararg depwarn

- Project.toml
- src/forwarddiff.jl
Fixes https://github.com/SciML/OrdinaryDiffEq.jl/issues/2091
> Fix type stability for duals

- src/forwarddiff.jl
- test/downstream/dual_detection_solution.jl
- test/runtests.jl
Fixes https://github.com/SciML/DiffEqBase.jl/issues/1003
> Specialize dual detection on solution types

- Project.toml
- src/callbacks.jl
fixes #997 #998, requires https://github.com/SciML/SciMLBase.jl/pull/625
> Fix discrete callback evaluation modification better

- src/callbacks.jl
> Run JuliaFormatter.format()

- Project.toml
- ext/DiffEqBaseReverseDiffExt.jl
Fixes https://github.com/SciML/DiffEqBase.jl/issues/1013
> Fix ReverseDiff Array of Structs to Struct of Array

- Project.toml
- src/forwarddiff.jl
- test/ode_default_norm.jl
> Fix norm of nested duals

- Project.toml
- ext/DiffEqBaseTrackerExt.jl
- src/solve.jl
Reverts SciML/DiffEqBase.jl#1030
> Revert "Incorrect ordering of promotion"

- src/common_defaults.jl
See if this simplifies things for GPU compilation
> Simplify default reduction and remove forced inlining

- ext/DiffEqBaseEnzymeExt.jl
Reverts SciML/DiffEqBase.jl#1054 @wsmoses @m-bossart
> Revert "use Enzyme make_zero"

- src/forwarddiff.jl
- test/forwarddiff_dual_detection.jl
Fully fixes https://github.com/SciML/DiffEqBase.jl/issues/1021
> Fix solutions nested in structs for forwarddiff

- src/callbacks.jl
Fixes https://github.com/SciML/DiffEqBase.jl/issues/1095#issuecomment-2417731614
> Remove other hasmethod from callbacks

- src/solve.jl
> docs: document late binding tstops

- test/downstream/community_callback_tests.jl
Some tolerance stuff and whatnot
> More test fixes

- Project.toml
- ext/DiffEqBaseForwardDiffExt.jl
- test/downstream/unitful.jl
Fixes https://github.com/SciML/OrdinaryDiffEq.jl/issues/2675
> Properly extend unitfulvalue

- .github/workflows/Tests.yml
- src/common_defaults.jl
- test/runtests.jl
- test/static/Project.toml
- test/static/static_checks.jl
Fixes https://github.com/SciML/DiffEqBase.jl/issues/1152
> Add static allocation checks and fix ComponentArrays allocs

- src/solve.jl
> fix: improve hack for null solution initialization

- ext/DiffEqBaseChainRulesCoreExt.jl
- ext/DiffEqBaseMooncakeExt.jl
- src/solve.jl
> fix MooncakeOriginator

- src/solve.jl
Should fix up downstream SciMLSensitivity Core 5
> Make sure to set MooncakeOriginator

- src/solve.jl
> fix: fix type-instability of `_get_root_indp`
